import 'package:lockerroom/model/quiz_question_model.dart';

final List<QuizQuestionModel> kboHistoryQuestions = [
  QuizQuestionModel(
    quizId: 'kbo_001',
    category: 'KBO역사',
    question: 'KBO리그가 출범한 연도는?',
    options: ['1982년', '1972년', '1980년', '1988년'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'KBO리그는 1982년에 출범했습니다.',
  ),

  QuizQuestionModel(
    quizId: 'kbo_002',
    category: 'KBO역사',
    question: '다음 중 KBO 원년(1982) 창단 구단이 아닌 팀은?',
    options: ['MBC청룡', 'OB베어스', '삼성라이온즈,', 'SSG랜더스'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation:
        '1982년 원년 구단은 MBC, OB, 삼성, 롯데, 삼미, 해태 여섯 팀이다.\n SSG는 2021년에 SK 와이번스를 인수하며 탄생한 최신 구단.',
  ),

  QuizQuestionModel(
    quizId: 'kbo_003',
    category: 'KBO역사',
    question: '다음 중 한국시리즈 최다 우승팀은?',
    options: ['두산베어스', '삼성라이온즈', '기아타이거즈', '롯데자이언츠'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '기아타이거즈는 한국시리즈 11회 우승으로 최다 우승팀입니다.',
  ),

  QuizQuestionModel(
    quizId: 'kbo_004',
    category: 'KBO역사',
    question: '한국시리즈에서 투수로서 4승을 올린 선수는?',
    options: ['류현진', '최동원', '박철순', '선동열'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '1984년 한국시리즈에서 최동원은 선발+구원으로 4승을 기록하여 롯데를 한국시리즈 우승으로 이끌었다.',
  ),

  QuizQuestionModel(
    quizId: 'kbo_005',
    category: 'KBO역사',
    question: 'KBO리그 한국시리즈 첫 우승팀은?',
    options: ['롯데자이언츠', '엘지트윈스', 'OB베어스(현 두산베어스)', '해태타이거즈(현 기아타이거즈)'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation:
        '1982년 10월12일 한국시리즈 6차전에서 삼성을 상대로 승리하며 \nKBO리그 한국시리즈 첫번째 우승팀이 되었다.',
  ),

  QuizQuestionModel(
    quizId: 'kbo_006',
    category: 'KBO역사',
    question: '투수로서 22연승을 달성한 선수는?',
    options: ['박철순', '최동원', '선동열', '류현진'],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '1982년 09월18일 박철순이 기록한 22연승',
  ),

  QuizQuestionModel(
    quizId: 'kbo_007',
    category: 'KBO역사',
    question: 'KBO리그 한경기 최다 17탈삼진을 기록한 선수는?',
    options: ['선동열', '윤석민', '니퍼트', '류현진'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: '류현진은 2010년 05월11일 청주 LG전에서 9이닝동안 17개의 삼진을 잡아내며 \n완투승을 기록하였다',
  ),

  QuizQuestionModel(
    quizId: 'kbo_008',
    category: 'KBO역사',
    question: 'KT 위즈가 KBO에 정식 참가한 연도는?',
    options: ['2013년', '2014년', '2015년', '2016년'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '2013~14년 퓨처스리그에서 뛰고, 2015년에 KBO리그에 참가했다.',
  ),

  QuizQuestionModel(
    quizId: 'kbo_009',
    category: 'KBO역사',
    question: '현대 유니콘스가 해체되면서 계보를 이어받아 탄생한 구단은?',
    options: ['롯데자이언츠', '엘지트윈스', 'NC다이노스', '키움히어로즈'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: '현대 → 히어로즈(넥센·키움)로 선수·기록 계보가 이어진다',
  ),

  QuizQuestionModel(
    quizId: 'kbo_0010',
    category: 'KBO역사',
    question: '2022년 KBO리그 최초 와이어 투 와이어 우승팀은?',
    options: ['롯데자이언츠', '엘지트윈스', '두산베어스', 'SSG랜더스'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation:
        '2022년 SSG랜더스는 시즌 개막때 부터 우승순간까지 1위자리를 놓치지 않아 \n와이어 투 와이어 우승이라는 KBO리그 최초의 기록을 달성하였다.',
  ),
];

final List<QuizQuestionModel> baseballRuelQuestions = [
  QuizQuestionModel(
    quizId: 'ruel_001',
    category: '야구룰',
    question: '1아웃 주자 1루 상황에 투수가 세트 포지션에서 정지자세 없이 투구를 할 경우 이 행동은 무엇인가',
    options: ['정상플레이', '보크', '볼', '타임'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '세트포지션에서 정지자세 없이 바로 투구를 하면 주자 기만행위로 보크로 선언된다',
  ),

  QuizQuestionModel(
    quizId: 'ruel_002',
    category: '야구룰',
    question: '스트라이크 존이란 무엇을 기준으로 정해질까?',
    options: ['심판 기분', '타자의 키', '타자의 어깨부터 무릎까지', '타자의 겨드랑이 아래 부분 ~ 무릎 윗부분'],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '겨드랑이 아래 부분 ~ 무릎 윗부분’이 공식 정의다',
  ),

  QuizQuestionModel(
    quizId: 'ruel_003',
    category: '야구룰',
    question: '타자가 공을 맞고 1루에 나가는 상황을 무엇이라 할까?',
    options: ['볼넷', '사구(데드볼)', '고의사구', '스윙'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '몸에 맞는 공 = 사구(HBP). 볼넷과 다르다.',
  ),

  QuizQuestionModel(
    quizId: 'ruel_004',
    category: '야구룰',
    question: '볼넷은 몇 개의 볼이 누적되면 성립할까?',
    options: ['4개', '2개', '3개', '1개'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '볼이 4개가 누적이 되면 볼넷이다',
  ),

  QuizQuestionModel(
    quizId: 'ruel_005',
    category: '야구룰',
    question: '주자가 없는 상황에서 홈런을 치면 몇 점일까?',
    options: ['1점', '2점', '3점', '4점'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '솔로 홈런 = 타자 혼자 들어오기 때문에 1점.',
  ),

  QuizQuestionModel(
    quizId: 'ruel_006',
    category: '야구룰',
    question: '외야 플라이가 잡히기 전 주자가 먼저 베이스 이탈 후 홈인했다. 점수는?',
    options: ['인정', '무조건 취소', '태그업 실패로 아웃', '수비가 어필해야 무효 처리'],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '태그업 실수는 수비팀이 ‘어필’해야 무효가 된다.',
  ),

  QuizQuestionModel(
    quizId: 'ruel_007',
    category: '야구룰',
    question: '1, 2, 3루에 주자가 모두 있는 상황을 뭐라 하나?',
    options: ['만루', '득점권', '풀베이스', '만원'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '1, 2, 3루 모두 주자가 있는 상황을 만루라고 한다.',
  ),

  QuizQuestionModel(
    quizId: 'ruel_008',
    category: '야구룰',
    question: '포수가 타자의 방망이를 건드렸다. 어떻게 되나?',
    options: ['플레이 계속', '타자에게 1루 부여', '파울볼', '타자 아웃'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '포수의 타격방해로 타자는 1루로 진루하고 모든 주자도 한 베이스씩 진루.',
  ),

  QuizQuestionModel(
    quizId: 'ruel_009',
    category: '야구룰',
    question: '무사 또는 1사, 주자 1·2루 또는 만루 상황에서 내야 뜬공은?',
    options: ['무조건 아웃', '인필드 플라이 룰 적용', '땅볼과 동일', '2루수만 잡으면 됨'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '인필드 플라이 룰이 적용되어 타자는 자동 아웃이지만 주자는 진루 가능.',
  ),

  QuizQuestionModel(
    quizId: 'ruel_0010',
    category: '야구룰',
    question: '3루 주자가 정규 투구 시 홈을 훔칠 수 있나?',
    options: ['불가능', '가능', '심판 허락 필요', '투수가 견제구를 던질 때만'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '규칙상 가능하지만 거의 시도되지 않는 위험한 플레이. 성공하면 홈스틸.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0011',
    category: '야구룰',
    question: '투수의 수비 번호는?',
    options: ['1', '2', '3', '4'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '투수의 수비 번호는 1번이다.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0012',
    category: '야구룰',
    question: '포수의 수비 번호는?',
    options: ['3', '2', '1', '5'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '포수의 수비 번호는 2번이다.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0013',
    category: '야구룰',
    question: '1루수의 수비 번호는?',
    options: ['7', '8', '3', '4'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '1루수의 수비 번호는 3번이다.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0014',
    category: '야구룰',
    question: '2루수의 수비 번호는?',
    options: ['6', '2', '3', '4'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: '2루수의 수비 번호는 4번이다.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0015',
    category: '야구룰',
    question: '3루수의 수비 번호는?',
    options: ['1', '5', '8', '4'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '3루수의 수비 번호는 5번이다.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0016',
    category: '야구룰',
    question: '유격수의 수비 번호는?',
    options: ['6', '7', '9', '4'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '유격수의 수비 번호는 6번이다.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0017',
    category: '야구룰',
    question: '좌익수의 수비 번호는?',
    options: ['7', '8', '9', '1'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '좌익수의 수비 번호는 7번이다.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0018',
    category: '야구룰',
    question: '중견수의 수비 번호는?',
    options: ['9', '7', '8', '4'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '중견수의 수비 번호는 8번이다.',
  ),
  QuizQuestionModel(
    quizId: 'ruel_0019',
    category: '야구룰',
    question: '우익수의 수비 번호는?',
    options: ['9', '6', '7', '4'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '우익수의 수비 번호는 9번이다.',
  ),
];

final List<QuizQuestionModel> playerQuestions = [
  QuizQuestionModel(
    quizId: 'player_001',
    category: '선수퀴즈',
    question: '한국인 최초 MLB 진출 선수는?',
    options: ['박찬호', '류현진', '추신수', '김병현'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '박찬호는 1994년 LA 다저스에 입단하며 한국인 최초 메이저리거가 되었다.',
  ),

  QuizQuestionModel(
    quizId: 'player_002',
    category: '선수퀴즈',
    question: '2006년 고졸 신인으로 18승을 거두며 MVP를 수상한 선수는?',
    options: ['김광현', '양현종', '류현진', '윤석민'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '류현진은 2006년 고졸 신인으로 18승 6패, 평균자책점 2.23을 기록하며 MVP를 수상했다.',
  ),

  QuizQuestionModel(
    quizId: 'player_003',
    category: '선수퀴즈',
    question: '2024년 기준 두산베어스 의 주전 포수는?',
    options: ['강민호', '양의지', '김태군', '유강남'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '양의지는 두산베어스의 주전 포수다',
  ),

  QuizQuestionModel(
    quizId: 'player_004',
    category: '선수퀴즈',
    question: 'KBO리그 역대 개인통산 최다 세이브 기록 보유선수는?',
    options: ['김택연', '조병현', '오승환', '김서현'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '2024년 04월24일 고척 키움전에서 세이브를 기록하며 개인통산 최다 세이브인 408세이브를 기록하였다.',
  ),

  QuizQuestionModel(
    quizId: 'player_005',
    category: '선수퀴즈',
    question: 'KBO리그 역대 개인통산 최다 홈런 기록 보유선수는?',
    options: ['이승엽', '최정', '이대호', '박병호'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '2024년 04월24일 부산 롯데전에서 통산 468홈런을 기록하였다.(이전기록: 이승엽(467홈런))',
  ),

  QuizQuestionModel(
    quizId: 'player_006',
    category: '선수퀴즈',
    question: 'KBO리그 역대 개인통산 최다 안타 기록 보유선수는?',
    options: ['이승엽', '최정', '손아섭', '박용택'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '2024년 06월20알 잠실 두산전에서 통산 2505안타를 기록하였다.(이전기록:박용택(2504안타))',
  ),

  QuizQuestionModel(
    quizId: 'player_007',
    category: '선수퀴즈',
    question: 'KBO리그 역대 개인통산 최다 탈삼진 기록 보유선수는?',
    options: ['니퍼트', '윤석민', '곽빈', '양현종'],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '2024년 08월21일 광주 롯데전에서 개인통산 2409 탈삼진을 기록하였다.',
  ),

  QuizQuestionModel(
    quizId: 'player_008',
    category: '선수퀴즈',
    question: 'KBO리그 역대 개인통산 최다 도루 기록 보유선수는?',
    options: ['이대형', '이종범', '전준호', '조수행'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '전준호는 통산 최다 549개의 도루를 기록하였다.',
  ),

  QuizQuestionModel(
    quizId: 'player_009',
    category: '선수퀴즈',
    question: 'KBO리그 2016시즌 다승왕은?',
    options: ['폰세', '니퍼트', '페디', '류현진'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '2016년 니퍼트는 시즌 22승을 기록하며 다승왕을 기록하였다.',
  ),

  QuizQuestionModel(
    quizId: 'player_0010',
    category: '선수퀴즈',
    question: 'KBO리그 역대 평균자책점 1위 기록 보유선수는?',
    options: ['류현진', '양현종', '김광현', '선동열'],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '선동열은 통산 평균자책점 0.99로 이 기록 1위를 기록하였다.',
  ),
];

final List<QuizQuestionModel> statsQuestions = [
  QuizQuestionModel(
    quizId: 'stats_001',
    category: '기록',
    question: '타율이 .300이라는 건 어떤 뜻일까?',
    options: ['30% 확률로 삼진', '30% 확률로 안타', '30% 확률로 출루', '30% 확률로 홈런'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '타율은 안타 ÷ 타수. .300은 10번 타석에 서면 3번 안타 친다는 뜻.',
  ),

  QuizQuestionModel(
    quizId: 'stats_002',
    category: '기록',
    question: 'OPS는 어떤 두 기록을 더한 값일까?',
    options: ['타율 + 장타율', '출루율 + 장타율', '타율 + 출루율', '출루율 + 삼진율'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'OPS = 출루율(OBP) + 장타율(SLG).‘출루 능력 + 장타력’을 한 번에 볼 수 있는 종합 지표',
  ),

  QuizQuestionModel(
    quizId: 'stats_003',
    category: '기록',
    question: 'ERA(평균자책점)가 낮다는 건 어떤 의미일까?',
    options: ['홈런을 많이 친다', '삼진을 잘 잡는다', '점수를 적게 준다', '볼넷이 많다'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'ERA는 투수가 9이닝 기준으로 몇 점을 책임지는지 보여주는 지표.',
  ),

  QuizQuestionModel(
    quizId: 'stats_004',
    category: '기록',
    question: 'wRC+가 100이라는 뜻은?',
    options: ['평균 대비 100홈런', '리그 평균과 동일한 공격력', '리그 최상급 공격력', '출루율이 1.00이다'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation:
        'wRC+는 리그·구장 보정 포함한 공격력 지표. 100 = 리그 평균, 120 = 평균 대비 20% 더 좋음.',
  ),

  QuizQuestionModel(
    quizId: 'stats_005',
    category: '기록',
    question: '규정타석을 채우지 못한 선수는 타율 1위를 달성할 수 있을까?',
    options: ['가능', '불가능', '심판재량', '팀 순위에 따라 다름'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation:
        '규정타석 미달이여도 규정타석까지 남은타석에서 모두 아웃으로 물러날 경우 타율이 1위라면 타격왕 수상이 가능하다(토니 그윈룰)',
  ),

  QuizQuestionModel(
    quizId: 'stats_006',
    category: '기록',
    question: 'WHIP은 어떤 투수 능력을 보여주는 지표일까?',
    options: ['홈런 허용력', '주자를 내보내는 빈도', '삼진 비율', '스윙률'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'WHIP = (볼넷 + 안타) ÷ 이닝. 투수가 1이닝당 몇 명을 내보내는지 보여주는 안정성 지표.',
  ),

  QuizQuestionModel(
    quizId: 'stats_007',
    category: '기록',
    question: '홈런(홈런 수)이 많다는 건 어떤 능력을 의미할까?',
    options: ['주루 능력', '장타력', '번트 능력', '수비 능력'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '홈런은 장타력(파워)의 상징적인 기록이다.',
  ),

  QuizQuestionModel(
    quizId: 'stats_008',
    category: '기록',
    question: '출루율(OBP)이 높은 타자는 어떤 특징을 가진 경우가 많을까?',
    options: ['삼진이 많다', '공을 잘 골라낸다', '홈런을 많이 친다', '도루가 많다'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '출루율은 안타 + 볼넷 + 사구가 포함되며, 특히 ‘볼넷을 많이 고르는 능력’ 이 중요하다',
  ),

  QuizQuestionModel(
    quizId: 'stats_009',
    category: '기록',
    question: '투수의 ‘삼진’ 개수(K)가 많은 건 어떤 장점의 의미일까?',
    options: ['수비 도움 없이 타자를 잡을 수 있다', '홈런을 잘 친다', '도루를 잘 막는다', '상대 팀이 좋아한다'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '삼진은 인플레이 타구가 없어 수비 운을 타지 않는다. 투수의 순수한 지배력 지표.',
  ),

  QuizQuestionModel(
    quizId: 'stats_0010',
    category: '기록',
    question: 'BABIP이 지나치게 높거나 낮으면 어떤 해석이 가능할까?',
    options: ['단순히 타격이 뛰어나다', '운(운빨)의 영향이 크다', '심판이 편파적이다', '팀 전술이 이상하다'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation:
        'BABIP(인플레이 타구 타율)은 운과 수비력의 영향을 크게 받는다. 너무 높거나 낮으면 실력보다 운의 영향이 큰 것.',
  ),
];

final List<QuizQuestionModel> cheerSongQuestions = [
  QuizQuestionModel(
    quizId: 'cheer_001',
    category: '응원가(인트로)',
    audioPath: 'audio/parkchanho.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['김민혁', '김상수', '박찬호', '정수빈'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '두산베어스 박찬호 응원가',
  ),

  QuizQuestionModel(
    quizId: 'cheer_002',
    category: '응원가(인트로)',
    audioPath: 'audio/loveEagles.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요?',
    options: ['삼성라이온즈', '기아타이거즈', '한화이글스', '두산베어스'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '한화이글스 사랑한다 이글스',
  ),

  QuizQuestionModel(
    quizId: 'cheer_003',
    category: '응원가(인트로)',
    audioPath: 'audio/winloud.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요?',
    options: ['기아타이거즈', '한화이글스', '키움히어로즈', 'NC다이노스'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '키움히어로즈 승리를 위한 함성',
  ),

  QuizQuestionModel(
    quizId: 'cheer_004',
    category: '응원가(인트로)',
    audioPath: 'audio/kimyoungwoong.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['김영웅', '김도영', '허경민', '양의지'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '삼성라이온즈 김영웅',
  ),

  QuizQuestionModel(
    quizId: 'cheer_005',
    category: '응원가(인트로)',
    audioPath: 'audio/jungsoobin.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['김도영', '정수빈', '이종욱', '디아즈'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '두산베어스 정수빈',
  ),

  QuizQuestionModel(
    quizId: 'cheer_006',
    category: '응원가(인트로)',
    audioPath: 'audio/yangEuiji.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['김도영', '양의지', '이종욱', '노시환'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '두산베어스 양의지',
  ),

  QuizQuestionModel(
    quizId: 'cheer_007',
    category: '응원가(인트로)',
    audioPath: 'audio/moonBoKyeong.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['문보경', '서호철', '이종욱', '노시환'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '엘지트윈스 문보경',
  ),

  QuizQuestionModel(
    quizId: 'cheer_008',
    category: '응원가(인트로)',
    audioPath: 'audio/leelowoon.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['최지훈', '양의지', '이종욱', '이로운'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'SSG랜더스 이로운(토코몬)',
  ),

  QuizQuestionModel(
    quizId: 'cheer_009',
    category: '응원가(인트로)',
    audioPath: 'audio/doowin.m4a',
    question: '이 응원가의 제목은?',
    options: ['승리를 위하여', '승리를 위한 함성', '마법의 성', '마산스트리트'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '두산베어스 승리를 위하여',
  ),

  QuizQuestionModel(
    quizId: 'cheer_010',
    category: '응원가(인트로)',
    audioPath: 'audio/magicCatle.m4a',
    question: '이 응원가의 제목은?',
    options: ['마법의 성', '위닝 KT', '엘도라도', '투혼의 랜더스'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'KT위즈 마법의 성',
  ),

  QuizQuestionModel(
    quizId: 'cheer_011',
    category: '응원가(인트로)',
    audioPath: 'audio/eldorado.m4a',
    question: '이 응원가의 제목은?',
    options: ['승리를 위하여', '마산스트리트', '엘도라도', '투혼의 랜더스'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '삼성라이온즈 엘도라도',
  ),

  QuizQuestionModel(
    quizId: 'cheer_012',
    category: '응원가(인트로)',
    audioPath: 'audio/kia1.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요?',
    options: ['기아타이거즈', 'SSG랜더스', '두산베어스', '롯데자이언츠'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '기아타이거즈 외쳐라 최강기아',
  ),

  QuizQuestionModel(
    quizId: 'cheer_013',
    category: '응원가(인트로)',
    audioPath: 'audio/victoryChant.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요?',
    options: ['기아타이거즈', 'SSG랜더스', '두산베어스', '롯데자이언츠'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: '롯데자이언츠 승전가',
  ),

  QuizQuestionModel(
    quizId: 'cheer_014',
    category: '응원가(인트로)',
    audioPath: 'audio/cryOutForVictory.m4a',
    question: '이 응원가의 제목은?',
    options: ['승리를 위하여', '승전가', '승리를 외치자', '영웅출정가'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '롯데자이언츠 승리를 외치자',
  ),

  QuizQuestionModel(
    quizId: 'cheer_015',
    category: '응원가(인트로)',
    audioPath: 'audio/doosanLineUpsong.m4a',
    question: '이 노래는 특정 팀의 라인업송 입니다. 어느 팀의 라인업 송 일까요?',
    options: ['키움히어로즈', '한화이글스', '두산베어스', '롯데자이언츠'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '두산베어스',
  ),

  QuizQuestionModel(
    quizId: 'cheer_016',
    category: '응원가(인트로)',
    audioPath: 'audio/fighting_spirit_Landers.m4a',
    question: '이 응원가의 제목은?',
    options: ['투혼의 랜더스', '엘도라도', '승리를 위하여', '외쳐라 최강기아'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'SSG랜더스 투혼의 랜더스',
  ),

  QuizQuestionModel(
    quizId: 'cheer_017',
    category: '응원가(인트로)',
    audioPath: 'audio/heroGo.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요?',
    options: ['기아타이거즈', '키움히어로즈', 'KT위즈', 'NC다이노스'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '키움히어로즈 영웅출정가',
  ),

  QuizQuestionModel(
    quizId: 'cheer_018',
    category: '응원가(인트로)',
    audioPath: 'audio/eaglesLineUp.m4a',
    question: '이 노래는 특정 팀의 라인업송 입니다. 어느 팀의 라인업 송 일까요?',
    options: ['기아타이거즈', '한화이글스', 'LG트윈스', '롯데자이언츠'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '한화이글스',
  ),

  QuizQuestionModel(
    quizId: 'cheer_019',
    category: '응원가(인트로)',
    audioPath: 'audio/moonHyunBin.m4a',
    question: '이 응원가의 주인공은?',
    options: ['김도영', '노시환', '문현빈', '양의지'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '한화이글스 문현빈 응원가',
  ),

  QuizQuestionModel(
    quizId: 'cheer_020',
    category: '응원가(인트로)',
    audioPath: 'audio/jeonMinJea.m4a',
    question: '이 응원가의 주인공은?',
    options: ['전준우', '전민재', '정철원', '이호준'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '롯데자이언츠 전민재',
  ),

  QuizQuestionModel(
    quizId: 'cheer_021',
    category: '응원가(인트로)',
    audioPath: 'audio/hongChangGi.m4a',
    question: '이 응원가의 주인공은?',
    options: ['오지환', '허경민', '김현수', '홍창기'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '엘지트윈스 홍창기',
  ),

  QuizQuestionModel(
    quizId: 'cheer_022',
    category: '응원가(인트로)',
    audioPath: 'audio/choiJung.m4a',
    question: '이 응원가의 주인공은?',
    options: ['최정', '황재균', '최지훈', '홍창기'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'SSG랜더스 최정',
  ),

  QuizQuestionModel(
    quizId: 'cheer_023',
    category: '응원가(인트로)',
    audioPath: 'audio/finalBoss.m4a',
    question: '이 노래의 주인공은?',
    options: ['오승환', '김택연', '김원중', '김병현'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '삼성라이온즈 오승환',
  ),
  QuizQuestionModel(
    quizId: 'cheer_024',
    category: '응원가(인트로)',
    audioPath: 'audio/rayyes.m4a',
    question: '이 응원가의 주인공은?',
    options: ['오스틴', '황재균', '최지훈', '레이예스'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '롯데자이언츠 레이예스',
  ),
  QuizQuestionModel(
    quizId: 'cheer_025',
    category: '응원가(인트로)',
    audioPath: 'audio/eredia.m4a',
    question: '이 응원가의 주인공은?',
    options: ['최정', '에레디아', '최지훈', '한유섬'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'SSG랜더스 에레디아',
  ),
  QuizQuestionModel(
    quizId: 'cheer_026',
    category: '응원가(인트로)',
    audioPath: 'audio/kimDoYoung.m4a',
    question: '이 응원가의 주인공은?',
    options: ['김도영', '안치홍', '최지훈', '심우준'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '기아타이거즈 김도영',
  ),
  QuizQuestionModel(
    quizId: 'cheer_027',
    category: '응원가(인트로)',
    audioPath: 'audio/cadines.m4a',
    question: '이 응원가의 주인공은?',
    options: ['최정', '카디네스', '송성문', '홍창기'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '키움히어로즈 카디네스',
  ),
  QuizQuestionModel(
    quizId: 'cheer_028',
    category: '응원가(인트로)',
    audioPath: 'audio/parkChanHyung.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박찬형', '안치홍', '강민호', '황성빈'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '롯데자이언츠 박찬형',
  ),
  QuizQuestionModel(
    quizId: 'cheer_029',
    category: '응원가(인트로)',
    audioPath: 'audio/ohSunWoo.m4a',
    question: '이 응원가의 주인공은?',
    options: ['한준수', '오선우', '김선빈', '소크라테스'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '기아타이거즈 오선우',
  ),
  QuizQuestionModel(
    quizId: 'cheer_030',
    category: '응원가(인트로)',
    audioPath: 'audio/kimGeonHe.m4a',
    question: '이 응원가의 주인공은?',
    options: ['송성문', '김건희', '이주형', '홍창기'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '키움히어로즈 김건희',
  ),
  QuizQuestionModel(
    quizId: 'cheer_031',
    category: '응원가(인트로)',
    audioPath: 'audio/kimHwiJip.m4a',
    question: '이 응원가의 주인공은?',
    options: ['최정', '황재균', '최지훈', '김휘집'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'NC다이노스 김휘집',
  ),
  QuizQuestionModel(
    quizId: 'cheer_032',
    category: '응원가(인트로)',
    audioPath: 'audio/ahnHyunMin.m4a',
    question: '이 응원가의 주인공은?',
    options: ['강백호', '황재균', '안현민', '홍창기'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'KT위즈 안현민',
  ),
  QuizQuestionModel(
    quizId: 'cheer_033',
    category: '응원가(인트로)',
    audioPath: 'audio/ohTaeGon.m4a',
    question: '이 응원가의 주인공은?',
    options: ['최정', '오태곤', '최지훈', '에레디아'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'SSG랜더스 오태곤',
  ),
  QuizQuestionModel(
    quizId: 'cheer_034',
    category: '응원가(인트로)',
    audioPath: 'audio/songSungMoon.m4a',
    question: '이 응원가의 주인공은?',
    options: ['송성문', '허경민', '최지훈', '홍창기'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '키움히어로즈 송성문',
  ),
  QuizQuestionModel(
    quizId: 'cheer_035',
    category: '응원가(인트로)',
    audioPath: 'audio/kimJuwon.m4a',
    question: '이 응원가의 주인공은?',
    options: ['김주원', '김휘집', '권희동', '김형준'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'NC다이노스 김주원',
  ),
  QuizQuestionModel(
    quizId: 'cheer_036',
    category: '응원가(인트로)',
    audioPath: 'audio/leeJaeHyun.m4a',
    question: '이 응원가의 주인공은?',
    options: ['이재현', '김영웅', '강민호', '홍창기'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '삼성라이온즈 이재현',
  ),
  QuizQuestionModel(
    quizId: 'cheer_037',
    category: '응원가(인트로)',
    audioPath: 'audio/parkSungHan.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박성한', '최정', '최지훈', '이지영'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'SSG랜더스 박성한',
  ),
  QuizQuestionModel(
    quizId: 'cheer_038',
    category: '응원가(인트로)',
    audioPath: 'audio/shinMinJae.m4a',
    question: '이 응원가의 주인공은?',
    options: ['오지환', '신민재', '최지훈', '홍창기'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '엘지트윈스 신민재',
  ),
  QuizQuestionModel(
    quizId: 'cheer_039',
    category: '응원가(인트로)',
    audioPath: 'audio/jungHoon.m4a',
    question: '이 응원가의 주인공은?',
    options: ['오지환', '정훈', '이대호', '홍창기'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '롯데자이언츠 정훈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_040',
    category: '응원가(인트로)',
    audioPath: 'audio/cave.m4a',
    question: '이 응원가의 주인공은?',
    options: ['오스틴', '케이브', '최지훈', '홍창기'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '두산베어스 케이브',
  ),
  QuizQuestionModel(
    quizId: 'cheer_041',
    category: '응원가(인트로)',
    audioPath: 'audio/liberato.m4a',
    question: '이 응원가의 주인공은?',
    options: ['리베라토', '디아즈', '케이브', '홍창기'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '한화이글스 리베라토',
  ),
  QuizQuestionModel(
    quizId: 'cheer_042',
    category: '응원가(인트로)',
    audioPath: 'audio/diaz.m4a',
    question: '이 응원가의 주인공은?',
    options: ['오지환', '디아즈', '최지훈', '홍창기'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '삼성라이온즈 디아즈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_043',
    category: '응원가(인트로)',
    audioPath: 'audio/kiaLineUp.m4a',
    question: '이 노래는 특정 팀의 라인업송 입니다. 어느 팀의 라인업 송 일까요?',
    options: ['기아타이거즈', '엘지트윈스', '두산베어스', '삼성라이온즈'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '기아타이거즈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_044',
    category: '응원가(인트로)',
    audioPath: 'audio/j.m4a',
    question: '이 응원가의 제목은?',
    options: ['남행열차', 'J에게', '그대에게', '아파트'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'SSG랜더스 J에게',
  ),
  QuizQuestionModel(
    quizId: 'cheer_045',
    category: '응원가(인트로)',
    audioPath: 'audio/chamPionDoosan.m4a',
    question: '이 응원가의 제목은?',
    options: ['야야야 두산', '챔피언 두산', '해야', '승리를 위하여'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '두산베어스 챔피언 두산',
  ),
  QuizQuestionModel(
    quizId: 'cheer_046',
    category: '응원가(인트로)',
    audioPath: 'audio/lgWinningSong.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요??',
    options: ['NC다이노스', '엘지 트윈스', '키움 히어로즈', 'KT위즈'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '엘지트윈스',
  ),
  QuizQuestionModel(
    quizId: 'cheer_047',
    category: '응원가(인트로)',
    audioPath: 'audio/heyaheya.m4a',
    question: '이 응원가의 제목은?',
    options: ['마법의 성', '해야해야', '승리를 위하여', '마산 스트리트'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '두산베어스 해야해야',
  ),
  QuizQuestionModel(
    quizId: 'cheer_048',
    category: '응원가(인트로)',
    audioPath: 'audio/weAreLanders.m4a',
    question: '이 응원가의 제목은?',
    options: ['서울의 아리아', '랜더스여', '영웅출정가', '엘도라도'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'SSG랜더스 랜더스여',
  ),
  QuizQuestionModel(
    quizId: 'cheer_049',
    category: '응원가(인트로)',
    audioPath: 'audio/ncLineUp.m4a',
    question: '이 노래는 특정 팀의 라인업송 입니다. 어느 팀의 라인업 송 일까요?',
    options: ['KT위즈', 'SSG랜더스', '두산베어스', 'NC다이노스'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: 'NC다이노스',
  ),
  QuizQuestionModel(
    quizId: 'cheer_050',
    category: '응원가(인트로)',
    audioPath: 'audio/kiwoomLineUp.m4a',
    question: '이 노래는 특정 팀의 라인업송 입니다. 어느 팀의 라인업 송 일까요?',
    options: ['KT위즈', 'SSG랜더스', '키움히어로즈', 'NC다이노스'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '키움히어로즈 라인업송',
  ),
  QuizQuestionModel(
    quizId: 'cheer_051',
    category: '응원가(가사)',
    audioPath: 'audio/leejuhyung.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n저 높이 날아올라 빛이되리라\n(OOOO OOO)',
    options: ['히어로즈 이주형', '다이노스 박민우', '자이언츠 윤동희', '라이온즈 디아즈'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '키움히어로즈 이주형',
  ),
  QuizQuestionModel(
    quizId: 'cheer_052',
    category: '응원가(인트로)',
    audioPath: 'audio/parkjuhong.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['박찬혁', '박주홍', '박찬호', '박경완'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '키움히어로즈 박주홍',
  ),
  QuizQuestionModel(
    quizId: 'cheer_053',
    category: '응원가(인트로)',
    audioPath: 'audio/parksoojong.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['이정후', '박주홍', '이주형', '박수종'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '키움히어로즈 박수종',
  ),
  QuizQuestionModel(
    quizId: 'cheer_054',
    category: '응원가(인트로)',
    audioPath: 'audio/leehyungjong.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['홍창기', '김혜성', '이정후', '이형종'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: '키움히어로즈 이형종',
  ),
  QuizQuestionModel(
    quizId: 'cheer_055',
    category: '응원가(인트로)',
    audioPath: 'audio/limjiyeol.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['임지열', '최주환', '박건우', '박민우'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '키움히어로즈 임지열',
  ),
  QuizQuestionModel(
    quizId: 'cheer_056',
    category: '응원가(인트로)',
    audioPath: 'audio/choijoowhan.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['최주환', '박병호', '오재일', '박건우'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '키움히어로즈 최주환',
  ),
  QuizQuestionModel(
    quizId: 'cheer_057',
    category: '응원가(인트로)',
    audioPath: 'audio/victoryloud.m4a',
    question: '이 응원가의 제목은?',
    options: ['승리를 위한 함성', '승리를 외치자', '승리를 위하여', '영웅출정가'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '키움히어로즈 승리를 위한 함성',
  ),
  QuizQuestionModel(
    quizId: 'cheer_058',
    category: '응원가(인트로)',
    audioPath: 'audio/wihayeo.m4a',
    question: '이 응원가의 제목은?',
    options: ['위하여', '마산스트리트', '영웅출정가', '야야야 두산'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'NC다이노스 위하여',
  ),
  QuizQuestionModel(
    quizId: 'cheer_059',
    category: '응원가(인트로)',
    audioPath: 'audio/ktWinningLoud.m4a',
    question: '이 응원가의 제목은?',
    options: ['마법의 성', '승리의 함성', '영웅출정가', '승리를 위하여'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'KT위즈 승리의 함성',
  ),
  QuizQuestionModel(
    quizId: 'cheer_060',
    category: '응원가(인트로)',
    audioPath: 'audio/ktLineUp.m4a',
    question: '이 노래는 특정 팀의 라인업 송 입니다. 어느 팀의 라인업 송 일까요?',
    options: ['롯데자이언츠', 'SSG랜더스', 'KT위즈', '두산베어스'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'KT위즈 라인업 송',
  ),
  QuizQuestionModel(
    quizId: 'cheer_061',
    category: '응원가(인트로)',
    audioPath: 'audio/ktHitSong.m4a',
    question: '이 노래는 특정 팀의 안타 송 입니다. 어느 팀의 안타 송 일까요?',
    options: ['KT위즈', '키움히어로즈', 'NC다이노스', 'LG트윈스'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'KT위즈 안타 송',
  ),
  QuizQuestionModel(
    quizId: 'cheer_062',
    category: '응원가(인트로)',
    audioPath: 'audio/togetherNc.m4a',
    question: '이 응원가의 주인공인 팀은?',
    options: ['NC다이노스', 'SSG랜더스', '롯데자이언츠', '두산베어스'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'NC다이노스 together Nc',
  ),
  QuizQuestionModel(
    quizId: 'cheer_063',
    category: '응원가(인트로)',
    audioPath: 'audio/kimMinHyeok.m4a',
    question: '이 응원가의 주인공은?',
    options: ['김민혁', '김상수', '강백호', '심우준'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'KT위즈 김민혁',
  ),
  QuizQuestionModel(
    quizId: 'cheer_064',
    category: '응원가(인트로)',
    audioPath: 'audio/beaJungDae.m4a',
    question: '이 응원가의 주인공은?',
    options: ['김민혁', '배정대', '박병호', '오재일'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'KT위즈 배정대',
  ),
  QuizQuestionModel(
    quizId: 'cheer_065',
    category: '응원가(인트로)',
    audioPath: 'audio/moonSangChul.m4a',
    question: '이 응원가의 주인공은?',
    options: ['문상철', '배정대', '허경민', '장성우'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'KT위즈 문상철',
  ),
  QuizQuestionModel(
    quizId: 'cheer_066',
    category: '응원가(인트로)',
    audioPath: 'audio/parkMinwoo.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박민우', '김주원', '서호철', '데이비슨'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'NC다이노스 박민우',
  ),
  QuizQuestionModel(
    quizId: 'cheer_067',
    category: '응원가(인트로)',
    audioPath: 'audio/davison.m4a',
    question: '이 응원가의 주인공은?',
    options: ['알테어', '테임즈', '데이비슨', '박민우'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'NC다이노스 데이비슨',
  ),
  QuizQuestionModel(
    quizId: 'cheer_068',
    category: '응원가(인트로)',
    audioPath: 'audio/kwonHeedong.m4a',
    question: '이 응원가의 주인공은?',
    options: ['권희동', '양의지', '박건우', '손시헌'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'NC다이노스 권희동',
  ),
  QuizQuestionModel(
    quizId: 'cheer_069',
    category: '응원가(인트로)',
    audioPath: 'audio/doTaeHoon.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박민우', '도태훈', '박건우', '김형준'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'NC다이노스 도태훈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_070',
    category: '응원가(인트로)',
    audioPath: 'audio/jeonJoonWoo.m4a',
    question: '이 응원가의 주인공은?',
    options: ['정훈', '이대호', '전준우', '김형준'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '롯데자이언츠 전준우',
  ),
  QuizQuestionModel(
    quizId: 'cheer_071',
    category: '응원가(인트로)',
    audioPath: 'audio/sonHoYoung.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박민우', '손호영', '한동희', '김형준'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '롯데자이언츠 손호영',
  ),
  QuizQuestionModel(
    quizId: 'cheer_072',
    category: '응원가(인트로)',
    audioPath: 'audio/yooGangNam.m4a',
    question: '이 응원가의 주인공은?',
    options: ['노진혁', '유강남', '한동희', '손성빈'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '롯데자이언츠 유강남',
  ),
  QuizQuestionModel(
    quizId: 'cheer_073',
    category: '응원가(인트로)',
    audioPath: 'audio/hwangSungBin.m4a',
    question: '이 응원가의 주인공은?',
    options: ['황성빈', '도태훈', '윤동희', '김형준'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '롯데자이언츠 황성빈',
  ),
  // QuizQuestionModel(
  //   quizId: 'cheer_074',
  //   category: '응원가(인트로)',
  //   audioPath: 'audio/naSeungYeop.m4a',
  //   question: '이 응원가의 주인공은?',
  //   options: ['이대호', '정훈', '나승엽', '황성빈'],
  //   correctIndex: 2,
  //   difficulty: 'easy',
  //   explanation: '롯데자이언츠 나승엽',
  // ),
  QuizQuestionModel(
    quizId: 'cheer_075',
    category: '응원가(인트로)',
    audioPath: 'audio/yoonDongHee.m4a',
    question: '이 응원가의 주인공은?',
    options: ['한동희', '황성빈', '전준우', '윤동희'],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '롯데자이언츠 윤동희',
  ),
  QuizQuestionModel(
    quizId: 'cheer_076',
    category: '응원가(인트로)',
    audioPath: 'audio/lotteTeamSong2.m4a',
    question: '이 응원가의 제목은?',
    options: ['승리의 순간', '영광의 순간', '승리를 위하여', '부산갈매기'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '롯데자이언츠 영광의 순간',
  ),
  QuizQuestionModel(
    quizId: 'cheer_077',
    category: '응원가(인트로)',
    audioPath: 'audio/lotteTeamSong.m4a',
    question: '이 응원가는 어떤 팀의 응원가 일까요? ',
    options: ['롯데자이언츠', 'NC다이노스', '기아타이거즈', '두산베어스'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '롯데자이언츠 우리들의 빛나는 이순간',
  ),
  QuizQuestionModel(
    quizId: 'cheer_078',
    category: '응원가(인트로)',
    audioPath: 'audio/doosanTeamSong3.m4a',
    question: '이 응원가의 제목은? ',
    options: ['해야', '최강두산', '승리의 두산', '락투더 두산'],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '두산베어스 해야',
  ),
  QuizQuestionModel(
    quizId: 'cheer_079',
    category: '응원가(인트로)',
    audioPath: 'audio/doosanTeamSong2.m4a',
    question: '이 응원가의 제목은? ',
    options: ['승리를 위하여', '해야', '두산 승리하리라', '야야야 두산'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '두산베어스 두산 승리하리라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_080',
    category: '응원가(인트로)',
    audioPath: 'audio/doosanFullCount.m4a',
    question: '이 응원가는 어떤 팀의 풀카운트 송 일까요? ',
    options: ['롯데자이언츠', 'NC다이노스', '기아타이거즈', '두산베어스'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '두산베어스 풀카운트 송',
  ),
  QuizQuestionModel(
    quizId: 'cheer_081',
    category: '응원가(인트로)',
    audioPath: 'audio/doosanBaseOnBall.m4a',
    question: '이 응원가는 어떤 팀의 볼넷 송 일까요? ',
    options: ['롯데자이언츠', 'NC다이노스', '기아타이거즈', '두산베어스'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '두산베어스 볼넷 송',
  ),
  QuizQuestionModel(
    quizId: 'cheer_082',
    category: '응원가(인트로)',
    audioPath: 'audio/doosanTeamSong.m4a',
    question: '이 응원가는 어떤 팀의 응원가 일까요? ',
    options: ['롯데자이언츠', '두산베어스', '기아타이거즈', '삼성라이온즈'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '두산베어스 승리의 두산',
  ),
  QuizQuestionModel(
    quizId: 'cheer_083',
    category: '응원가(인트로)',
    audioPath: 'audio/kimInTae.m4a',
    question: '이 응원가는 누구의 응원가 일까요? ',
    options: ['강승호', '박계범', '김인태', '오명진'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '두산베어스 김인태',
  ),
  QuizQuestionModel(
    quizId: 'cheer_084',
    category: '응원가(인트로)',
    audioPath: 'audio/leeYooChan.m4a',
    question: '이 응원가는 누구의 응원가 일까요? ',
    options: ['박찬호', '이유찬', '김대한', '안재석'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '두산베어스 이유찬',
  ),
  QuizQuestionModel(
    quizId: 'cheer_085',
    category: '응원가(인트로)',
    audioPath: 'audio/joSooHeng.m4a',
    question: '이 응원가는 누구의 응원가 일까요? ',
    options: ['조수행', '서현숙', '양석환', '정수빈'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '두산베어스 조수행',
  ),
  QuizQuestionModel(
    quizId: 'cheer_086',
    category: '응원가(인트로)',
    audioPath: 'audio/yangSeokWhan.m4a',
    question: '이 응원가는 누구의 응원가 일까요? ',
    options: ['오명진', '양의지', '양석환', '정수빈'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '두산베어스 양석환',
  ),
  QuizQuestionModel(
    quizId: 'cheer_087',
    category: '응원가(가사)',
    audioPath: 'audio/ncTeamSong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n외쳐라NC여~\n(OOOOO OO OOO)',
    options: ['다이노스의 승리위하여~', '다이노스의 정상위하여~', '다이노스의 우승위하여~', '다이노스의 연승위하여~'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '다이노스의 승리위하여~',
  ),
  QuizQuestionModel(
    quizId: 'cheer_088',
    category: '응원가(가사)',
    audioPath: 'audio/ncTeamSong2.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n정든 그곳을 등지고서 난 떠나왔네~\n(OOOO OOO)',
    options: ['승리가득 안고서', '꿈을가득 안고서', '목표가득 안고서', '희망가득 안고서'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '꿈을가득 안고서',
  ),
  QuizQuestionModel(
    quizId: 'cheer_089',
    category: '응원가(가사)',
    audioPath: 'audio/lgTeamSong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n외쳐라 무적LG~(O OOOO OO)',
    options: ['LG의 승리위해~', '자 모두함께 LG', '자 승리하라 LG', '자 불태워라 LG'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '자 승리하라 LG',
  ),
  QuizQuestionModel(
    quizId: 'cheer_090',
    category: '응원가(가사)',
    audioPath: 'audio/leeJungHoo.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n키움 히어로 이정후\n(OOOOOO OOOOO)',
    options: ['홈런홈런홈런 날려버려라', '가자가자가자 날려버려라', '끝내끝내끝내 날려버려라', '안타안타안타 날려버려라'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '안타안타안타 날려버려라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_091',
    category: '응원가(가사)',
    audioPath: 'audio/kimHyeSeong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n김혜성 히어로즈 김혜성~\n(O OO OOO OOOO)',
    options: [
      '저 꿈을 밝히는 혜성처럼',
      '저 멀리 빛나는 혜성처럼',
      '저 하늘 빛나는 혜성처럼',
      '저 하늘 스치는 혜성처럼',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '저 하늘 빛나는 혜성처럼',
  ),
  QuizQuestionModel(
    quizId: 'cheer_092',
    category: '응원가(가사)',
    audioPath: 'audio/heroesTeamSong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n오오 울려퍼져라 이곳에~(OOOOO OO)',
    options: ['다이노스의 노래', '자이언츠의 노래', '히어로즈의 노래', '타이거즈의 노래'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '히어로즈의 노래',
  ),
  QuizQuestionModel(
    quizId: 'cheer_093',
    category: '응원가(가사)',
    audioPath: 'audio/doosanTeamSong4.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n깨끗하고 힘차게~(OOO OOOO)',
    options: ['승리의 그날까지', '승리의 영광까지', '영원한 나의친구', '승리의 순간까지'],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '승리의 순간까지',
  ),
  QuizQuestionModel(
    quizId: 'cheer_094',
    category: '응원가(가사)',
    audioPath: 'audio/kimMinSeok.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n두산의 김민석~(OOO OO OOO)',
    options: ['힘차게 치고 달려라', '저멀리 치고 달려라', '안타를 날려라', '안타안타안타 안타'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '힘차게 치고 달려라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_095',
    category: '응원가(가사)',
    audioPath: 'audio/miracleDoosanBears.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n미라클 두산베어스~(OOOO OOO)',
    options: ['뜨거운 열정이', '그대이름 베어스', '그대이름 챔피언', '그대안에 열정이'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '그대이름 챔피언',
  ),
  QuizQuestionModel(
    quizId: 'cheer_096',
    category: '응원가(가사)',
    audioPath: 'audio/kimJiChan.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n삼성의 김지찬~(OOO OOO)',
    options: ['저멀리 날려라', '빠르게 달려라', '안타를 날려라', '홈런을 날려라'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '안타를 날려라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_097',
    category: '응원가(가사)',
    audioPath: 'audio/choiHyngWoo.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n넌 주인공 인거야~(OOOOO OOO)',
    options: ['오늘내일도 영원히', '지금이대로 영원히', '언제까지나 평생을', '언제까지나 영원히'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '언제까지나 영원히',
  ),
  QuizQuestionModel(
    quizId: 'cheer_098',
    category: '응원가(가사)',
    audioPath: 'audio/kimSungYoon.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n더 멀리 더 빨리~(OO OOO)',
    options: ['홈런 날려라', '안타 날려라', '치고 달려라', '빨리 뛰어라'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '치고 달려라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_099',
    category: '응원가(가사)',
    audioPath: 'audio/samsungLineUp.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n최강삼성 오 라이온즈여~\n(OOOO OOO)',
    options: ['승리한다 우리는', '기억하라 우리는', '기억한다 우리는', '기억하라 승리는'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '기억하라 우리는',
  ),
  QuizQuestionModel(
    quizId: 'cheer_100',
    category: '응원가(가사)',
    audioPath: 'audio/samsungTeamSong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n우리는 승리의~(OOOO OOOO)',
    options: ['승리하라 라이온즈', '최강삼성 라이온즈', '영원하라 라이온즈', '승리한다 라이온즈'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '최강삼성 라이온즈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_101',
    category: '응원가(가사)',
    audioPath: 'audio/kiaTeamSong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n승리하라 최강기아~(OOOO OOOO)',
    options: ['열광한다 타이거즈', '최강기아 타이거즈', '승리하라 타이거즈', '열광하라 타이거즈'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '열광하라 타이거즈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_102',
    category: '응원가(가사)',
    audioPath: 'audio/kiaTeamSong2.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n남행열차에~(OOOO OO OOO)',
    options: ['흔들리는 철길 너머로', '흔들리는 마음 너머로', '흔들리는 차창 너머로', '흔들리는 열차 너머로'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '흔들리는 차창 너머로',
  ),
  QuizQuestionModel(
    quizId: 'cheer_103',
    category: '응원가(가사)',
    audioPath: 'audio/kimDoYoung2.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n김도영 힘차게 날려라~(OOO OOO OOO)',
    options: ['기아의 영광을 위하여', '오놀의 승리를 위하여', '김도영 승리를 위하여', '기아의 승리를 위하여'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '기아의 승리를 위하여',
  ),
  QuizQuestionModel(
    quizId: 'cheer_104',
    category: '응원가(가사)',
    audioPath: 'audio/hanHwaLineUp.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n승리를 위하여~(OOOO)',
    options: ['랜더스여', '트윈스여', '베어스여', '이글스여'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '이글스여',
  ),
  QuizQuestionModel(
    quizId: 'cheer_105',
    category: '응원가(가사)',
    audioPath: 'audio/chaeEnSung.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n저 하늘로 날아올라~(OO OOO)',
    options: ['승리 되리라', '빛이 되리라', '홈런 되리라', '안타 되리라'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '빛이 되리라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_106',
    category: '응원가(가사)',
    audioPath: 'audio/lgTeamSong2.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n다같이 외쳐라~(OOO OOO)',
    options: ['승리의 함성을', '엘지의 함성을', '우리의 함성을', '팬들의 함성을'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '우리의 함성을',
  ),
  QuizQuestionModel(
    quizId: 'cheer_107',
    category: '응원가(가사)',
    audioPath: 'audio/lgTeamSong3.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n승리의 함성을~(OOO OOO)',
    options: ['다같이 외쳐라', '다함께 외쳐라', '힘차게 외쳐라', '신나게 외쳐라'],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '다같이 외쳐라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_108',
    category: '응원가(인트로)',
    audioPath: 'audio/lgTeamSong3.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요?',
    options: ['NC다이노스', 'LG트윈스', '두산베어스', '롯데자이언츠'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'LG트윈스 승리의 노래',
  ),
  QuizQuestionModel(
    quizId: 'cheer_109',
    category: '응원가(인트로)',
    audioPath: 'audio/landersTeamSong4.m4a',
    question: '이 응원가의 제목은?',
    options: ['J에게', '연안부두', '부산갈매기', '남행열차'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'SSG랜더스 연안부두',
  ),
  QuizQuestionModel(
    quizId: 'cheer_110',
    category: '응원가(가사)',
    audioPath: 'audio/landersTeamSong3.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n랜더스 이름으로~(OO OOOO)',
    options: ['우리 하나되어', '모두 하나되어', '함께 하나되어', '같이 하나되어'],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '우리 하나되어',
  ),
  QuizQuestionModel(
    quizId: 'cheer_111',
    category: '응원가(인트로)',
    audioPath: 'audio/landersTeamSong3.m4a',
    question: '이 응원가의 제목은?',
    options: ['랜더스여', '프론티어 랜더스', '나가자 랜더스', '승리의 랜더스'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '프론티어 랜더스',
  ),
  QuizQuestionModel(
    quizId: 'cheer_112',
    category: '응원가(가사)',
    audioPath: 'audio/landersTeamSong2.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n오오오오오오오오오~\n(OOO OOO OOO)',
    options: ['랜더스 승리로 나가자', '랜더스 승리를 외친다', '랜더스 승리를 외쳐라', '랜더스 승리를 외치자'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '랜더스 승리를 외쳐라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_113',
    category: '응원가(인트로)',
    audioPath: 'audio/landersTeamSong2.m4a',
    question: '이 응원가는 어느 팀의 응원가 일까요?',
    options: ['롯데자이언츠', 'KT위즈', '키움히어로즈', 'SSG랜더스'],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'SSG랜더스 승리를 외쳐라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_114',
    category: '응원가(가사)',
    audioPath: 'audio/winningFlag.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\nWe Are Landers 승리한다~(OOO OO OOO)',
    options: ['깃발을 높이 올려라', '힘차게 달려 나가자', '승리를 위해 나가자', '목소릴 높이 올려라'],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '깃발을 높이 올려라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_115',
    category: '응원가(인트로)',
    audioPath: 'audio/winningFlag.m4a',
    question: '이 응원가의 제목은?',
    options: ['깃발을 높이 올려라', 'We Are Landers', '승리의 깃발', '랜더스여'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '승리의 깃발',
  ),
  QuizQuestionModel(
    quizId: 'cheer_116',
    category: '응원가(가사)',
    audioPath: 'audio/landersTeamSong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n우리의 열정을 하나로 모아~(OOOO OOO OO OOO)',
    options: [
      '날아올라 승리를 향해 나가자',
      '날아올라 정상을 향해 나가자',
      '달려가자 승리를 향해 나가자',
      '달려가자 정상을 향해 나가자',
    ],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '날아올라 정상을 향해 나가자',
  ),
  QuizQuestionModel(
    quizId: 'cheer_117',
    category: '응원가(인트로)',
    audioPath: 'audio/landersTeamSong.m4a',
    question: '이 응원가의 제목은?',
    options: ['랜더스여', '승리의 깃발', '투혼의 랜더스', '프론티어 랜더스'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'SSG랜더스 랜더스여',
  ),
  QuizQuestionModel(
    quizId: 'cheer_118',
    category: '응원가(가사)',
    audioPath: 'audio/landersLineUp.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n우리의 함성으로~(OOOO OOO)',
    options: ['이글스의 승리를', '트윈스의 승리를', '베어스의 승리를', '랜더스의 승리를'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '랜더스의 승리를',
  ),
  QuizQuestionModel(
    quizId: 'cheer_119',
    category: '응원가(인트로)',
    audioPath: 'audio/landersLineUp.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요?',
    options: ['KT위즈', 'LG트윈스', 'SSG랜더스', '기아타이거즈'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'SSG랜더스 라인업 송',
  ),
  QuizQuestionModel(
    quizId: 'cheer_120',
    category: '응원가(인트로)',
    audioPath: 'audio/leeJinYoung.m4a',
    question: '이 응원가의 주인공은?',
    options: ['이진영', '이원석', '노시환', '문현빈'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '한화이글스 이진영',
  ),
  QuizQuestionModel(
    quizId: 'cheer_121',
    category: '응원가(가사)',
    audioPath: 'audio/leeJinYoung.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n이 순간 너의 모든것을 보여줘~(O OOOOO)',
    options: ['넌 이원석이다', '넌 이도윤이다', '넌 노시환이다', '넌 이진영이다'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '넌 이진영이다',
  ),
  QuizQuestionModel(
    quizId: 'cheer_122',
    category: '응원가(인트로)',
    audioPath: 'audio/ohMyungJin.m4a',
    question: '이 응원가의 주인공은?',
    options: ['안재석', '강승호', '오명진', '이유찬'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '두산베어스 오명진',
  ),
  QuizQuestionModel(
    quizId: 'cheer_123',
    category: '응원가(인트로)',
    audioPath: 'audio/hwangYongMook.m4a',
    question: '이 응원가의 주인공은?',
    options: ['문현빈', '황영묵', '윤준호', '류현인'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '한화이글스 황영묵',
  ),
  QuizQuestionModel(
    quizId: 'cheer_124',
    category: '응원가(가사)',
    audioPath: 'audio/hwangYongMook.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요! 한화의 승리를~(OOOO)',
    options: ['원하잖아', '바라잖아', '향하잖아', '원하니까'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '원하잖아',
  ),
  QuizQuestionModel(
    quizId: 'cheer_125',
    category: '응원가(인트로)',
    audioPath: 'audio/cheonSungHo.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['천성호', '강백호', '심우준', '문보경'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'LG트윈스 천성호',
  ),
  QuizQuestionModel(
    quizId: 'cheer_126',
    category: '응원가(인트로)',
    audioPath: 'audio/kimHungJoon.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박세혁', '김형준', '권희동', '박민우'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'NC다이노스 김형준',
  ),
  QuizQuestionModel(
    quizId: 'cheer_127',
    category: '응원가(인트로)',
    audioPath: 'audio/choiInHo.m4a',
    question: '이 응원가의 주인공은?',
    options: ['최인호', '황영묵', '채은성', '최재훈'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '한화이글스 최인호',
  ),
  // QuizQuestionModel(
  //   quizId: 'cheer_128',
  //   category: '응원가(인트로)',
  //   audioPath: 'audio/kimDongHyuk.m4a',
  //   question: '이 응원가의 주인공은?',
  //   options: ['김동혁', '한동희', '윤동희', '전민재'],
  //   correctIndex: 0,
  //   difficulty: 'easy',
  //   explanation: '롯데자이언츠 김동혁',
  // ),
  QuizQuestionModel(
    quizId: 'cheer_129',
    category: '응원가(인트로)',
    audioPath: 'audio/simWooJoon.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['이재원', '심우준', '이도윤', '최인호'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '한화이글스 심우준',
  ),
  QuizQuestionModel(
    quizId: 'cheer_130',
    category: '응원가(인트로)',
    audioPath: 'audio/leeWonSeok.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['이재원', '이원석', '이도윤', '최인호'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '한화이글스 이원석',
  ),
  QuizQuestionModel(
    quizId: 'cheer_131',
    category: '응원가(가사)',
    audioPath: 'audio/lotteTeamSong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n나의열정 꿈의 그라운드~\n(OOO OOO O OOO OOOO)',
    options: [
      '우리의 찬란한 이 순간을 기억하라',
      '우리의 빛나는 이 순간을 기억하라',
      '우리의 뜨거운 이 순간을 기억하라',
      '우리의 눈부신 이 순간을 기억하라',
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '우리의 빛나는 이 순간을 기억하라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_132',
    category: '응원가(가사)',
    audioPath: 'audio/heroesTeamSong2.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n창공의 백구는~(OOOO OOO)',
    options: ['전광판을 가르고', '조명탑을 가르고', '함성속을 가르고', '하늘위를 가르고'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '전광판을 가르고',
  ),
  QuizQuestionModel(
    quizId: 'cheer_133',
    category: '응원가(인트로)',
    audioPath: 'audio/byeonWooHyuck.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['변우혁', '이원석', '최원준', '최인호'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '기아타이거즈 변우혁',
  ),
  QuizQuestionModel(
    quizId: 'cheer_134',
    category: '응원가(인트로)',
    audioPath: 'audio/hanYuSeom.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['한유섬', '추신수', '최지훈', '고명준'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'SSG랜더스 한유섬',
  ),
  QuizQuestionModel(
    quizId: 'cheer_135',
    category: '응원가(인트로)',
    audioPath: 'audio/choiJiHoon.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['변우혁', '최지훈', '박성한', '최정'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'SSG랜더스 최지훈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_136',
    category: '응원가(인트로)',
    audioPath: 'audio/parkHeaMin.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['김현수', '박해민', '정수빈', '최정'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'LG트윈스 박해민',
  ),
  QuizQuestionModel(
    quizId: 'cheer_137',
    category: '응원가(인트로)',
    audioPath: 'audio/parkDongWon.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['양의지', '박동원', '김태군', '최정'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'LG트윈스 박동원',
  ),
  QuizQuestionModel(
    quizId: 'cheer_138',
    category: '응원가(인트로)',
    audioPath: 'audio/bigBoy.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['박동원', '이재원', '문보경', '문성주'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'LG트윈스 이재원',
  ),
  QuizQuestionModel(
    quizId: 'cheer_139',
    category: '응원가(인트로)',
    audioPath: 'audio/hanDongHee.m4a',
    question: '이 응원가의 주인공은 누구일까요?',
    options: ['전민재', '한동희', '윤동희', '최향'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '롯데자이언츠 한동희',
  ),
  QuizQuestionModel(
    quizId: 'cheer_140',
    category: '응원가(인트로)',
    audioPath: 'audio/DoosanNewTeamSong.m4a',
    question: '이 응원가는 어느팀의 응원가 일까요?',
    options: ['두산베어스', 'LG트윈스', '롯데자이언츠', '키움히어로즈'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '두산베어스 서울의 베어스',
  ),
  QuizQuestionModel(
    quizId: 'cheer_141',
    category: '응원가(가사)',
    audioPath: 'audio/DoosanNewTeamSong.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n하늘의 가득찬~(OOO OO)',
    options: ['우리의 함성', '승리의 함성', '뜨거운 함성', '희망의 함성'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '우리의 함성',
  ),
  QuizQuestionModel(
    quizId: 'cheer_142',
    category: '응원가(인트로)',
    audioPath: 'audio/Cameron.m4a',
    question: '이 응원가의 주인공은?',
    options: ['케이브', '소크라테스', '카메론', '위즈덤'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '두산베어스 카메론',
  ),
  QuizQuestionModel(
    quizId: 'cheer_143',
    category: '응원가(인트로)',
    audioPath: 'audio/HongSungHo.m4a',
    question: '이 응원가의 주인공은?',
    options: ['홍성흔', '홍성호', '허경민', '이유찬'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '두산베어스 홍성호',
  ),
  QuizQuestionModel(
    quizId: 'cheer_144',
    category: '응원가(인트로)',
    audioPath: 'audio/KimMinHeok.m4a',
    question: '이 응원가의 주인공은?',
    options: ['김민혁', '양석환', '김인태', '김기연'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '두산베어스 김민혁',
  ),
  QuizQuestionModel(
    quizId: 'cheer_145',
    category: '응원가(인트로)',
    audioPath: 'audio/ParkJiHoon.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박지훈', '안재석', '최지훈', '박성한'],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '두산베어스 박지훈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_146',
    category: '응원가(가사)',
    audioPath: 'audio/ParkJiHoon2.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n승리위해~(OO OOO OOO)',
    options: ['안타 날려라 박지훈', '홈런 날려라 박지훈', '열정 모아라 박지훈', '승리 위해서 박지훈'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: '안타 날려라 박지훈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_147',
    category: '응원가(인트로)',
    audioPath: 'audio/ParkJunSoon.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박지훈', '오명진', '김주오', '박준순'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: '두산베어스 박준순',
  ),
  QuizQuestionModel(
    quizId: 'cheer_148',
    category: '응원가(가사)',
    audioPath: 'audio/ParkJunSoon2.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n두산의 승리위해~(OO OOO)',
    options: ['치고 달려라', '함께 뛰어라', '홈런 날려라', '안타 날려라'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '치고 달려라',
  ),
  QuizQuestionModel(
    quizId: 'cheer_149',
    category: '응원가(인트로)',
    audioPath: 'audio/RohSiHwan.m4a',
    question: '이 응원가의 주인공은?',
    options: ['김도영', '노시환', '문보경', '구자욱'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '한화이글스 노시환',
  ),
  QuizQuestionModel(
    quizId: 'cheer_150',
    category: '응원가(가사)',
    audioPath: 'audio/RohSiHwan.m4a',
    question: '🎵 노래를 듣고 빈칸을 채워보세요!\n날려줘요~(OOOOO)',
    options: ['열정적으로', '환상적으로', '압도적으로', '희망적으로'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '환상적으로',
  ),
  QuizQuestionModel(
    quizId: 'cheer_151',
    category: '응원가(인트로)',
    audioPath: 'audio/WisDom.m4a',
    question: '이 응원가의 주인공은?',
    options: ['소크라테스', '위즈덤', '나성범', '오선우'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '기아타이거즈 위즈덤',
  ),
  QuizQuestionModel(
    quizId: 'cheer_152',
    category: '응원가(인트로)',
    audioPath: 'audio/MoonSungJu.m4a',
    question: '이 응원가의 주인공은?',
    options: ['문보경', '오지환', '문성주', '오스틴'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'LG트윈스 문성주',
  ),
  QuizQuestionModel(
    quizId: 'cheer_153',
    category: '응원가(인트로)',
    audioPath: 'audio/CheonJaeHwan.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박민우', '박건우', '천재환', '김형준'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'NC다이노스 천재환',
  ),
  QuizQuestionModel(
    quizId: 'cheer_154',
    category: '응원가(인트로)',
    audioPath: 'audio/LeeHoJun.m4a',
    question: '이 응원가의 주인공은?',
    options: ['이호준', '이대호', '전준우', '유강남'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '롯데자이언츠 이호준',
  ),
  QuizQuestionModel(
    quizId: 'cheer_155',
    category: '응원가(인트로)',
    audioPath: 'audio/ParkJiHwan.m4a',
    question: '이 응원가의 주인공은?',
    options: ['박성한', '정준재', '박지환', '고명준'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'SSG랜더스 박지환',
  ),
  QuizQuestionModel(
    quizId: 'cheer_156',
    category: '응원가(인트로)',
    audioPath: 'audio/KimSeongWook.m4a',
    question: '이 응원가의 주인공은?',
    options: ['김성욱', '최정', '정준재', '박지환'],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: 'SSG랜더스 김성욱',
  ),
  QuizQuestionModel(
    quizId: 'cheer_157',
    category: '응원가(인트로)',
    audioPath: 'audio/NohJinHyeok.m4a',
    question: '이 응원가의 주인공은?',
    options: ['황성빈', '전준우', '손성빈', '노진혁'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: '롯데자이언츠 노진혁',
  ),
  QuizQuestionModel(
    quizId: 'cheer_158',
    category: '응원가(인트로)',
    audioPath: 'audio/LotteNewTeamSong.m4a',
    question: '이 응원가의 제목은?',
    options: ['승리를 위해', '영광을 위해', '영광을 향해', '승리의 순간'],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '롯데자이언츠 영광을 위해',
  ),
  QuizQuestionModel(
    quizId: 'cheer_159',
    category: '응원가(인트로)',
    audioPath: 'audio/ParkSeungWook.m4a',
    question: '이 응원가의 주인공은?',
    options: ['정보근', '최지훈', '박승욱', '조수행'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '롯데자이언츠 박승욱',
  ),
  QuizQuestionModel(
    quizId: 'cheer_160',
    category: '응원가(인트로)',
    audioPath: 'audio/SonSungBin.m4a',
    question: '이 응원가의 주인공은?',
    options: ['유강남', '양의지', '강민호', '손성빈'],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: '롯데자이언츠 손성빈',
  ),
  QuizQuestionModel(
    quizId: 'cheer_161',
    category: '응원가(인트로)',
    audioPath: 'audio/HanTaeYang.m4a',
    question: '이 응원가의 주인공은?',
    options: ['허경민', '정훈', '한태양', '권희동'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '롯데자이언츠 한태양',
  ),
  QuizQuestionModel(
    quizId: 'cheer_162',
    category: '응원가(인트로)',
    audioPath: 'audio/KimMinSung.m4a',
    question: '이 응원가의 주인공은?',
    options: ['구본혁', '안재석', '김민성', '김성욱'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '롯데자이언츠 김민성',
  ),
  QuizQuestionModel(
    quizId: 'cheer_164',
    category: '응원가(인트로)',
    audioPath: 'audio/Peraja.m4a',
    question: '이 응원가의 주인공은?',
    options: ['안재석', '전준우', '페라자', '김성욱'],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '한화이글스 페라자',
  ),
];

// 랜덤 카테고리 문제 (모든 카테고리에서 섞은 문제들)
final List<QuizQuestionModel> randomQuestions = [
  // KBO역사에서
  QuizQuestionModel(
    quizId: 'random_001',
    category: '랜덤',
    question: 'KBO리그가 출범한 연도는?',
    options: ['1982년', '1972년', '1980년', '1988년'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'KBO리그는 1982년에 출범했습니다.',
  ),
  QuizQuestionModel(
    quizId: 'random_002',
    category: '랜덤',
    question: '다음 중 한국시리즈 최다 우승팀은?',
    options: ['두산베어스', '삼성라이온즈', '기아타이거즈', '롯데자이언츠'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '기아타이거즈는 한국시리즈 11회 우승으로 최다 우승팀입니다.',
  ),

  // 야구룰에서
  QuizQuestionModel(
    quizId: 'random_003',
    category: '랜덤',
    question: '볼넷은 몇 개의 볼이 누적되면 성립할까?',
    options: ['4개', '2개', '3개', '1개'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '볼이 4개가 누적이 되면 볼넷이다',
  ),
  QuizQuestionModel(
    quizId: 'random_004',
    category: '랜덤',
    question: '1, 2, 3루에 주자가 모두 있는 상황을 뭐라 하나?',
    options: ['만루', '득점권', '풀베이스', '만원'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '1, 2, 3루 모두 주자가 있는 상황을 만루라고 한다.',
  ),

  // 선수퀴즈에서
  QuizQuestionModel(
    quizId: 'random_005',
    category: '랜덤',
    question: '한국인 최초 MLB 진출 선수는?',
    options: ['박찬호', '류현진', '추신수', '김병현'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '박찬호는 1994년 LA 다저스에 입단하며 한국인 최초 메이저리거가 되었다.',
  ),
  QuizQuestionModel(
    quizId: 'random_006',
    category: '랜덤',
    question: 'KBO리그 역대 개인통산 최다 홈런 기록 보유선수는?',
    options: ['이승엽', '최정', '이대호', '박병호'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '2024년 04월24일 부산 롯데전에서 통산 468홈런을 기록하였다.',
  ),

  // 기록에서
  QuizQuestionModel(
    quizId: 'random_007',
    category: '랜덤',
    question: '타율이 .300이라는 건 어떤 뜻일까?',
    options: ['30% 확률로 삼진', '30% 확률로 안타', '30% 확률로 출루', '30% 확률로 홈런'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '타율은 안타 ÷ 타수. .300은 10번 타석에 서면 3번 안타 친다는 뜻.',
  ),
  QuizQuestionModel(
    quizId: 'random_008',
    category: '랜덤',
    question: 'OPS는 어떤 두 기록을 더한 값일까?',
    options: ['타율 + 장타율', '출루율 + 장타율', '타율 + 출루율', '출루율 + 삼진율'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'OPS = 출루율(OBP) + 장타율(SLG).',
  ),

  // 추가 혼합 문제
  QuizQuestionModel(
    quizId: 'random_009',
    category: '랜덤',
    question: '한국시리즈에서 투수로서 4승을 올린 선수는?',
    options: ['류현진', '최동원', '박철순', '선동열'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '1984년 한국시리즈에서 최동원은 선발+구원으로 4승을 기록하여 롯데를 한국시리즈 우승으로 이끌었다.',
  ),
  QuizQuestionModel(
    quizId: 'random_010',
    category: '랜덤',
    question: 'KBO리그 역대 개인통산 최다 세이브 기록 보유선수는?',
    options: ['김택연', '조병현', '오승환', '김서현'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '오승환은 개인통산 최다 세이브인 408세이브를 기록하였다.',
  ),
  QuizQuestionModel(
    quizId: 'random_011',
    category: '랜덤',
    question: '주자가 없는 상황에서 홈런을 치면 몇 점일까?',
    options: ['1점', '2점', '3점', '4점'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '솔로 홈런 = 타자 혼자 들어오기 때문에 1점.',
  ),
  QuizQuestionModel(
    quizId: 'random_012',
    category: '랜덤',
    question: 'KT 위즈가 KBO에 정식 참가한 연도는?',
    options: ['2013년', '2014년', '2015년', '2016년'],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '2013~14년 퓨처스리그에서 뛰고, 2015년에 KBO리그에 참가했다.',
  ),
  QuizQuestionModel(
    quizId: 'random_013',
    category: '랜덤',
    question: 'ERA(평균자책점)가 낮다는 건 어떤 의미일까?',
    options: ['홈런을 많이 친다', '삼진을 잘 잡는다', '점수를 적게 준다', '볼넷이 많다'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'ERA는 투수가 9이닝 기준으로 몇 점을 책임지는지 보여주는 지표.',
  ),
  QuizQuestionModel(
    quizId: 'random_014',
    category: '랜덤',
    question: '2022년 KBO리그 최초 와이어 투 와이어 우승팀은?',
    options: ['롯데자이언츠', '엘지트윈스', '두산베어스', 'SSG랜더스'],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '2022년 SSG랜더스는 시즌 개막때 부터 우승순간까지 1위자리를 놓치지 않았다.',
  ),
  QuizQuestionModel(
    quizId: 'random_015',
    category: '랜덤',
    question: 'KBO리그 역대 평균자책점 1위 기록 보유선수는?',
    options: ['류현진', '양현종', '김광현', '선동열'],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '선동열은 통산 평균자책점 0.99로 이 기록 1위를 기록하였다.',
  ),

  // 응원가에서
  QuizQuestionModel(
    quizId: 'random_016',
    category: '랜덤',
    audioPath: 'audio/yangEuiji.m4a',
    question: '이 응원가는 누구의 응원가 일까요?',
    options: ['김도영', '양의지', '이종욱', '노시환'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '두산베어스 양의지',
  ),
  QuizQuestionModel(
    quizId: 'random_017',
    category: '랜덤',
    audioPath: 'audio/magicCatle.m4a',
    question: '이 응원가의 제목은?',
    options: ['마법의 성', '위닝 KT', '엘도라도', '투혼의 랜더스'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'KT위즈 마법의 성',
  ),
  QuizQuestionModel(
    quizId: 'random_018',
    category: '랜덤',
    audioPath: 'audio/eldorado.m4a',
    question: '이 응원가의 제목은?',
    options: ['승리를 위하여', '마산스트리트', '엘도라도', '투혼의 랜더스'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '삼성라이온즈 엘도라도',
  ),
  QuizQuestionModel(
    quizId: 'random_019',
    category: '랜덤',
    audioPath: 'audio/doowin.m4a',
    question: '이 응원가의 제목은?',
    options: ['승리를 위하여', '승리를 위한 함성', '마법의 성', '마산스트리트'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '두산베어스 승리를 위하여',
  ),
  QuizQuestionModel(
    quizId: 'random_020',
    category: '랜덤',
    audioPath: 'audio/choiJung.m4a',
    question: '이 응원가의 주인공은?',
    options: ['최정', '황재균', '최지훈', '홍창기'],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'SSG랜더스 최정',
  ),
];
