import 'package:flutter/cupertino.dart';
import 'package:lockerroom/model/food_store_model.dart';

class FoodStoreProvider extends ChangeNotifier {
  final Map<String, List<FoodStoreModel>> _foodStoreList = {
    '잠실야구장': [
      FoodStoreModel(
        storeName: '통밥',
        location: '1루내야 2.5층, 3루내야 2층',
        type: '한식',
        storePhoto: 'assets/images/logo/ttonbbab.jpeg',
      ),
      FoodStoreModel(storeName: '원샷치킨', location: '3루외부', type: '치킨'),
      FoodStoreModel(storeName: '원샷치킨_1루광장', location: '1루광장', type: '치킨'),
      FoodStoreModel(storeName: '원샷치킨_3루광장', location: ' 3루광장', type: '치킨'),
      FoodStoreModel(
        storeName: '원샷치킨_내야상단',
        location: '331블럭 상단, 304블럭 상단',
        type: '치킨',
      ),
      FoodStoreModel(
        storeName: '이가네 떡볶이',
        location: '1루내야 2층, 3루광장',
        type: '분식',
        storePhoto: 'assets/images/logo/igane.png',
      ),
      FoodStoreModel(
        storeName: '명인만두',
        location: '1,3루 내야 2층, 외야외부',
        type: '분식',
        storePhoto: 'assets/images/logo/myungin.png',
      ),
      FoodStoreModel(
        storeName: '미스터 피자',
        location: '3루 내야 2층',
        type: '피자',
        storePhoto: 'assets/images/logo/mrpizza.png',
      ),
      FoodStoreModel(
        storeName: '프랭크 버거',
        location: '외부, 1,3루 내야 2층, 1루내야 3층',
        type: '버거',
        storePhoto: 'assets/images/logo/frank.png',
      ),
      FoodStoreModel(
        storeName: 'BBQ/꼬꼬닭',
        location: '1,3루 내야 2층',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: '죠스떡볶이',
        location: '3루광장',
        type: '분식',
        storePhoto: 'assets/images/logo/shark.png',
      ),
      FoodStoreModel(
        storeName: '브리쉘 프라이',
        location: '1루내야 2.5층',
        type: '감자튀김',
        storePhoto: 'assets/images/logo/brussels.jpg',
      ),
      FoodStoreModel(
        storeName: '짝태패밀리',
        location: '3루내야 2.5층',
        type: '건어물',
        storePhoto: 'assets/images/logo/zzactea.jpeg',
      ),
      FoodStoreModel(
        storeName: 'GS25',
        location: '외부 1,3루 내야, 외야',
        type: '편의점',
        storePhoto: 'assets/images/logo/gs25_logo.png',
      ),
      FoodStoreModel(
        storeName: '신철판 야채곱창',
        location: '1루 내야 출입문 우측',
        type: '한식',
      ),
      FoodStoreModel(
        storeName: 'BBQ치킨',
        location: '3루외부',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: 'BBQ치킨_외야',
        location: '외야외부',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: 'BBQ치킨_3루내야 ',
        location: '3루내야 2층',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),

      FoodStoreModel(
        storeName: 'BBQ치킨_1루내야',
        location: '1루내야 2층, 1루내야 3층',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '3루외부',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: '1964백미당',
        location: '1루내야 2층',
        type: '커피, 음료',
        storePhoto: 'assets/images/logo/1964.jpg',
      ),
      FoodStoreModel(
        storeName: 'OBC 수제맥주',
        location: '1루내야 2층',
        type: '수제맥주',
        storePhoto: 'assets/images/logo/obc.png',
      ),
      FoodStoreModel(
        storeName: '앤티엔스프레즐',
        location: '1루내야 2층',
        type: '프레즐',
        storePhoto: 'assets/images/logo/aunti.png',
      ),
      FoodStoreModel(
        storeName: '미스터피자',
        location: '3루외부, 3루광장',
        type: '피자',
        storePhoto: 'assets/images/logo/mrpizza.png',
      ),
      FoodStoreModel(storeName: '카페바른생활', location: '3루외부', type: '커피,음료'),
      FoodStoreModel(
        storeName: '자문밖',
        location: '3루외부',
        type: '국수,떡갈비',
        storePhoto: 'assets/images/logo/jamoon.png',
      ),
      FoodStoreModel(storeName: '수내닭꼬치', location: '외야외부, 3루광장', type: '닭꼬치'),
      FoodStoreModel(
        storeName: '달콤커피',
        location: '1루광장',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/dalkomm.png',
      ),
      FoodStoreModel(
        storeName: 'KFC치킨',
        location: '1루외부, 3루내야 2,3층',
        type: '치킨',
        storePhoto: 'assets/images/logo/kfc.png',
      ),
      FoodStoreModel(storeName: '광장식당', location: '1루외부', type: '분식'),
      FoodStoreModel(storeName: '꼬꼬닭 닭강정', location: '1루외부', type: '닭강정'),
      FoodStoreModel(
        storeName: '도미노 피자',
        location: '1루외부',
        type: '피자',
        storePhoto: 'assets/images/logo/domino.png',
      ),
      FoodStoreModel(storeName: '홈런마트', location: '1루외부', type: '편의점'),
      FoodStoreModel(
        storeName: 'XOXO핫도그',
        location: '3루광장',
        type: '핫도그,음료',
        storePhoto: 'assets/images/logo/xoxo.jpg',
      ),
      FoodStoreModel(
        storeName: '갑또리 닭강정',
        location: '1루내야 광장, 3루내야 2층',
        type: '닭강정',
      ),
      FoodStoreModel(
        storeName: '달콤커피',
        location: '3루내야 2층',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/dalkomm.png',
      ),
      FoodStoreModel(
        storeName: '요아정',
        location: '3루내야 2층',
        type: '요거트',
        storePhoto: 'assets/images/logo/yoajung.png',
      ),
      FoodStoreModel(
        storeName: '와팡',
        location: '3루내야 2,3층',
        type: '와플아이스크림',
        storePhoto: 'assets/images/logo/wafpang.png',
      ),
      FoodStoreModel(storeName: '카페그라운드', location: '3루내야 2층', type: '커피,음료'),
      FoodStoreModel(
        storeName: '피자헛',
        location: '1루내야 2층, 3루내야 2층',
        type: '피자',
        storePhoto: 'assets/images/logo/pizzahut.png',
      ),
      FoodStoreModel(
        storeName: '스테프핫도그',
        location: '1루내야3층, 3루내야 3층',
        type: '핫도그',
        storePhoto: 'assets/images/logo/steff.jpg',
      ),
      FoodStoreModel(storeName: '야구애꼬치다', location: '316블럭 상단', type: '꼬치'),
      FoodStoreModel(
        storeName: '올떡',
        location: '318블럭 상단',
        type: '분식',
        storePhoto: 'assets/images/logo/alltokk.png',
      ),
    ],

    '고척스카이돔': [
      FoodStoreModel(
        storeName: '쉬림프 셰프_내야',
        location: '내야 3번 게이트 ',
        type: '크림새우',
        storePhoto: 'assets/images/logo/shirimp.png',
      ),
      FoodStoreModel(
        storeName: '쉬림프 셰프_외야',
        location: '외야 4층 21번 게이트 ',
        type: '크림새우',
        storePhoto: 'assets/images/logo/shirimp.png',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '내야 3번 게이트 ',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: '메머드커피_내야',
        location: '내야 3번, 11번 게이트 ',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/mamoth.png',
      ),
      FoodStoreModel(
        storeName: '메머드커피_외야',
        location: '외야 4번 게이트 ',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/mamoth.png',
      ),
      FoodStoreModel(
        storeName: '멕시카나치킨',
        location: '내야 4번 게이트 ',
        type: '치킨',
        storePhoto: 'assets/images/logo/mexicana.jpg',
      ),
      FoodStoreModel(
        storeName: '쉬림프 셰프',
        location: '내야 3번 게이트 ',
        type: '크림새우',
        storePhoto: 'assets/images/logo/shirimp.png',
      ),
      FoodStoreModel(
        storeName: '유부빚는마을',
        location: '내야 5번 게이트 , 외야 1번 게이트 ',
        type: '고기세트',
        storePhoto: 'assets/images/logo/yuboo.webp',
      ),
      FoodStoreModel(storeName: '제일버거', location: '내야 2번 게이트 ', type: '햄버거'),
      FoodStoreModel(storeName: '펠리스돔', location: '내야 5번 게이트 ', type: '샌드위치'),
      FoodStoreModel(storeName: '제일버거', location: '내야 2번 게이트 ', type: '햄버거'),
      FoodStoreModel(
        storeName: '편밀밀',
        location: '내야 4번 게이트 ',
        type: '분식',
        storePhoto: 'assets/images/logo/milmil.png',
      ),
      FoodStoreModel(storeName: '편의점', location: '내야 2, 11번 게이트 ', type: '편의점'),
      FoodStoreModel(storeName: '피자', location: '내야 2번 게이트 ', type: '피자'),
      FoodStoreModel(
        storeName: 'BBQ',
        location: '내야 10번 게이트',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: '맘스터치',
        location: '내야 10번 게이트',
        type: '햄버거',
        storePhoto: 'assets/images/logo/moms.webp',
      ),
      FoodStoreModel(
        storeName: '마왕족발',
        location: '내야 9번 게이트 ',
        type: '족발',
        storePhoto: 'assets/images/logo/mawang.png',
      ),
      FoodStoreModel(
        storeName: '스테프핫도그',
        location: '내야 11번 게이트',
        type: '핫도그',
        storePhoto: 'assets/images/logo/steff.jpg',
      ),
      FoodStoreModel(
        storeName: '자담치킨',
        location: '내야 10번 게이트',
        type: '치킨',
        storePhoto: 'assets/images/logo/jadam.jpg',
      ),
      FoodStoreModel(
        storeName: '스트릿 츄러스',
        location: '내야 8번 게이트 ',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(
        storeName: '올떡볶이',
        location: '내야 4,9번 게이트',
        type: '분식',
        storePhoto: 'assets/images/logo/alltokk.png',
      ),
      FoodStoreModel(
        storeName: '초장집',
        location: '내야 10번 게이트 ',
        type: '육회',
        storePhoto: 'assets/images/logo/chojang.png',
      ),
      FoodStoreModel(
        storeName: '올떡볶이',
        location: '외야 2번 게이트 ',
        type: '분식',
        storePhoto: 'assets/images/logo/alltokk.png',
      ),
      FoodStoreModel(
        storeName: '자담치킨',
        location: '외야 3번 게이트 ',
        type: '치킨',
        storePhoto: 'assets/images/logo/jadam.jpg',
      ),
      FoodStoreModel(
        storeName: 'BBQ',
        location: '외야 4번 게이트 ',
        type: '치킨,',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: '맘스터치',
        location: '외야 4번 게이트 ',
        type: '햄버거',
        storePhoto: 'assets/images/logo/moms.webp',
      ),
      FoodStoreModel(
        storeName: '닭강정, BHC',
        location: '외야 4번 게이트 ',
        type: '닭강정, 치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: '스테프핫도그',
        location: '외야 4번 게이트 ',
        type: '핫도그',
        storePhoto: 'assets/images/logo/steff.jpg',
      ),
      FoodStoreModel(storeName: '멘야파이토', location: '외야 3번 게이트 ', type: '라멘'),
      FoodStoreModel(
        storeName: '제일버거, 요거트',
        location: '외야 4층 26번 게이트 ',
        type: '햄버거, 요거트',
      ),
    ],

    '랜더스필드': [
      FoodStoreModel(
        storeName: 'STATION',
        location: '1루 202섹션 ',
        type: '크림새우',
        storePhoto: 'assets/images/logo/station.png',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '1루 2층 203섹션 ',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(storeName: '패밀리푸드존', location: '1루 2층 203섹션 ', type: '분식'),
      FoodStoreModel(
        storeName: '노랑통닭',
        location: '1루 2층 201섹션 ',
        type: '치킨',
        storePhoto: 'assets/images/logo/norang.png',
      ),
      FoodStoreModel(
        storeName: '노브랜드버거',
        location: '1루 2층 201섹션',
        type: '햄버거',
        storePhoto: 'assets/images/logo/nobrand.png',
      ),
      FoodStoreModel(storeName: '몬칩 팩토리', location: '1루 2층 202섹션', type: '닭강정'),
      FoodStoreModel(
        storeName: '허갈닭강정/문학철판삼겹',
        location: '1루 2층 202섹션',
        type: '닭강정/삼겹살',
        storePhoto: 'assets/images/logo/hugal.jpg',
      ),
      FoodStoreModel(
        storeName: '씬난다스테이크&마라새우',
        location: '1루 2층 202섹션',
        type: '스테이크/마라새우',
      ),
      FoodStoreModel(
        storeName: '스타벅스',
        location: '1루 2층 201섹션',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/starbucks.png',
      ),
      FoodStoreModel(storeName: '커빙', location: '1루 2층 202섹션', type: '커피,음료'),
      FoodStoreModel(
        storeName: '우리동네 미미네',
        location: '1루 4층 316섹션',
        type: '편의점',
        storePhoto: 'assets/images/logo/mimine.png',
      ),
      FoodStoreModel(
        storeName: '파파존스',
        location: '1루 4층 313섹션',
        type: '피자',
        storePhoto: 'assets/images/logo/papajons.png',
      ),
      FoodStoreModel(storeName: '먹거리 분식', location: '3루 2층 204섹션', type: '분식'),
      FoodStoreModel(
        storeName: '쌈빠치킨 떡볶이',
        location: '3루 2층 206섹션',
        type: '치킨,떡볶이',
      ),
      FoodStoreModel(
        storeName: '이마트24',
        location: '3루 2층 206섹션',
        type: '편의점',
        storePhoto: 'assets/images/logo/emart24.png',
      ),
      FoodStoreModel(storeName: '킹콩떡볶이', location: '3루 2층 205섹션', type: '분식'),
      FoodStoreModel(
        storeName: 'BHC/드림마켓',
        location: '1루 1층 103섹션',
        type: '치킨,편의점',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: '스타벅스2호점',
        location: '1루 1층 104섹션',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/starbucks.png',
      ),
      FoodStoreModel(
        storeName: '스트릿츄러스',
        location: '1루 1층 103섹션',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(
        storeName: 'pick me 31',
        location: '1루 1층 103섹션',
        type: '와인',
      ),
      FoodStoreModel(storeName: 'T mart', location: '1루 1층 105섹션', type: '편의점'),
      FoodStoreModel(
        storeName: '국대떡볶이',
        location: '1루 1층 105섹션',
        type: '분식',
        storePhoto: 'assets/images/logo/gookdae.jpg',
      ),
      FoodStoreModel(storeName: '버거트레일러', location: '1루 1층 102섹션', type: '햄버거'),
      FoodStoreModel(
        storeName: '우리동네 미미네_1층',
        location: '1루 1층 104섹션',
        type: '분식',
        storePhoto: 'assets/images/logo/mimine.png',
      ),
      FoodStoreModel(
        storeName: '이마트24_1층',
        location: '1루 1층 102섹션',
        type: '편의점',
        storePhoto: 'assets/images/logo/emart24.png',
      ),
      FoodStoreModel(
        storeName: '오레오츄러스',
        location: '3루 1층 109섹션',
        type: '츄러스',
        storePhoto: 'assets/images/logo/oreo.webp',
      ),
      FoodStoreModel(
        storeName: '북촌손만두',
        location: '3루 1층 107섹션',
        type: '만두',
        storePhoto: 'assets/images/logo/bookchon.png',
      ),
      FoodStoreModel(
        storeName: '푸라닭',
        location: '3루 1층 108섹션',
        type: '치킨',
        storePhoto: 'assets/images/logo/puradak.png',
      ),
      FoodStoreModel(
        storeName: '오사카야끼,그루터기',
        location: '3루 1층 108섹션',
        type: '야끼소바, 스낵',
      ),
      FoodStoreModel(
        storeName: '순살싸다리',
        location: '1루외야 2층 바비큐존',
        type: '크림새우,치킨',
      ),
      FoodStoreModel(
        storeName: '명인만두',
        location: '1루 외야 2층',
        type: '만두,족발',
        storePhoto: 'assets/images/logo/myungin.png',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨_외야',
        location: '1루 외야 2층 204블럭',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: '크리스피도넛',
        location: '1루 외야 2층',
        type: '도넛',
        storePhoto: 'assets/images/logo/krispy.jpg',
      ),
      FoodStoreModel(
        storeName: '스트릿츄러스',
        location: '1루 외야 2층',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(storeName: '우이락 고추튀김', location: '1루 외야 2층', type: '고추튀김'),
      FoodStoreModel(
        storeName: '블루시드 커피',
        location: '1루 외야 2층 204블럭',
        type: '커피,음료',
      ),
      FoodStoreModel(
        storeName: '야구사랑',
        location: '1루 외야 2층 204블럭',
        type: '크림새우',
      ),
      FoodStoreModel(
        storeName: '민영활어공장',
        location: '3루 외부',
        type: '초밥/물회',
        storePhoto: 'assets/images/logo/minyoung.jpeg',
      ),
    ],

    '위즈파크': [
      FoodStoreModel(storeName: '끼부리또', location: '1루 2층 하단', type: '부리또,타코'),
      FoodStoreModel(storeName: '또리펍', location: '1루 2층 하단', type: '맥주'),
      FoodStoreModel(
        storeName: '롯데리아',
        location: '1루 2층 상단',
        type: '햄버거',
        storePhoto: 'assets/images/logo/lotteria.png',
      ),
      FoodStoreModel(storeName: '빅카페', location: '1루 2층 하단', type: '커피,음료'),
      FoodStoreModel(
        storeName: '세븐일레븐_1루',
        location: '1루 매장',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐_1루내야',
        location: '1루 내야 GATE2',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(storeName: '솜사탕', location: '1루 GATE4', type: '솜사탕'),
      FoodStoreModel(storeName: '이대로 통삼겹', location: '1루 2층 하단', type: '삼겹살'),
      FoodStoreModel(
        storeName: '파파존스',
        location: '1루 2층 상단',
        type: '피자',
        storePhoto: 'assets/images/logo/papajons.png',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '1루 2층 하단',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: '브리쉘프라이',
        location: '1루 2층 하단',
        type: '감자튀김',
        storePhoto: 'assets/images/logo/brussels.jpg',
      ),
      FoodStoreModel(
        storeName: '오늘의 초밥',
        location: '1루 2층 하단',
        type: '초밥',
        storePhoto: 'assets/images/logo/today.png',
      ),
      FoodStoreModel(
        storeName: '스트릿 츄러스',
        location: '1루 2층 상단',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(
        storeName: '완미족발',
        location: '1루 2층 싱단',
        type: '족발',
        storePhoto: 'assets/images/logo/wanmi.jpg',
      ),
      FoodStoreModel(storeName: '또리펍_3루', location: '3루 2층 하단', type: '맥주'),
      FoodStoreModel(storeName: '빅카페_3루', location: '3루 2층 하단', type: '커피,음료'),
      FoodStoreModel(storeName: '삼구삼진 휴게소', location: '3루 2층 싱단', type: '스낵'),
      FoodStoreModel(
        storeName: '샐러리아',
        location: '3루 2층 싱단',
        type: '포케',
        storePhoto: 'assets/images/logo/saleria.jpeg',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐_3루',
        location: '3루 2층 하단',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(
        storeName: '쉬림프 쉐프',
        location: '3루 2층 하단',
        type: '크림새우',
        storePhoto: 'assets/images/logo/shirimp.png',
      ),
      FoodStoreModel(storeName: '홈런분식', location: '3루 2층 하단', type: '분식'),
      FoodStoreModel(storeName: '메가닭꼬치', location: '3루 2층 싱단', type: '닭꼬치'),
      FoodStoreModel(
        storeName: '보영만두',
        location: '3루 2층 하단',
        type: '만두,쫄면',
        storePhoto: 'assets/images/logo/boyoung.jpeg',
      ),
      FoodStoreModel(
        storeName: '본수원갈비',
        location: '3루 2층 하단',
        type: 'LA갈비',
        storePhoto: 'assets/images/logo/bonsuwon.png',
      ),
      FoodStoreModel(storeName: '삼미제빵소', location: '3루 2층 싱단', type: '빵,쿠키'),
      FoodStoreModel(
        storeName: '요거트월드',
        location: '3루 2층 하단',
        type: '요거트 아이스크림',
        storePhoto: 'assets/images/logo/yogurtworld.png',
      ),
      FoodStoreModel(storeName: '전설의곱창', location: '3루 2층 히단', type: '곱창'),
      FoodStoreModel(
        storeName: '정지영커피',
        location: '3루 2층 하단',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/jungjiyoung.png',
      ),
      FoodStoreModel(
        storeName: '진미통닭',
        location: '3루 2층 하단',
        type: '치킨',
        storePhoto: 'assets/images/logo/jinmi.png',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐_3루 5층',
        location: '3루 5층',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐_3루 중앙',
        location: '3루 중앙',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐_외야',
        location: '외야 중앙 테라스',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(storeName: '빅또리카페', location: '외부 1층 중앙', type: '커피,음료'),
      FoodStoreModel(
        storeName: '세븐일레븐_외부',
        location: '외부 1층 중앙',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
    ],

    '한화생명볼파크': [
      FoodStoreModel(
        storeName: 'BBQ치킨',
        location: '1층 107구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: 'GS25',
        location: '1층 101구역',
        type: '편의점',
        storePhoto: 'assets/images/logo/gs25_logo.png',
      ),
      FoodStoreModel(
        storeName: '명랑핫도그',
        location: '1층 104구역',
        type: '핫도그',
        storePhoto: 'assets/images/logo/myngrang.jpg',
      ),
      FoodStoreModel(
        storeName: '원조 바로그집',
        location: '1루 111구역',
        type: '분식',
        storePhoto: 'assets/images/logo/wonjo.png',
      ),
      FoodStoreModel(
        storeName: '반올림피자',
        location: '1루 105구역',
        type: '피자',
        storePhoto: 'assets/images/logo/banolim.jpg',
      ),
      FoodStoreModel(
        storeName: '북촌손만두',
        location: '1루 107구역',
        type: '만두',
        storePhoto: 'assets/images/logo/bookchon.png',
      ),
      FoodStoreModel(
        storeName: '선비꼬마김밥',
        location: '1루 111구역',
        type: '분식',
        storePhoto: 'assets/images/logo/sunbi.png',
      ),
      FoodStoreModel(
        storeName: '완미족발',
        location: '1루 109구역',
        type: '족발',
        storePhoto: 'assets/images/logo/wanmi.jpg',
      ),
      FoodStoreModel(
        storeName: '이글스브루어리/오수리',
        location: '1루 102구역',
        type: '버터구이 오징어',
        storePhoto: 'assets/images/logo/osuri3.png',
      ),
      FoodStoreModel(
        storeName: '자담치킨',
        location: '1루 107구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/jadam.jpg',
      ),
      FoodStoreModel(
        storeName: 'BBQ치킨',
        location: '1층 101구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: 'BBQ치킨',
        location: '중앙 100B구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: '공차',
        location: '중앙 100C구역',
        type: '버블티',
        storePhoto: 'assets/images/logo/gongcha.png',
      ),
      FoodStoreModel(
        storeName: 'GS25',
        location: '중앙 100B구역',
        type: '편의점',
        storePhoto: 'assets/images/logo/gs25_logo.png',
      ),
      FoodStoreModel(
        storeName: '반올림피자',
        location: '중앙 100B구역',
        type: '피자',
        storePhoto: 'assets/images/logo/banolim.jpg',
      ),
      FoodStoreModel(
        storeName: '완미족발',
        location: '중앙 100B구역',
        type: '족발',
        storePhoto: 'assets/images/logo/wanmi.jpg',
      ),
      FoodStoreModel(
        storeName: '은구비 커피',
        location: '중앙 100A구역',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/eungubi.jpg',
      ),
      FoodStoreModel(
        storeName: '이글스브루어리',
        location: '중앙 100C구역',
        type: '맥주',
        storePhoto: 'assets/images/logo/brewary.png',
      ),
      FoodStoreModel(
        storeName: '이닝스',
        location: '중앙 100C구역',
        type: '핫도그',
        storePhoto: 'assets/images/logo/innings.png',
      ),
      FoodStoreModel(
        storeName: '자담치킨',
        location: '중앙 100B구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/jadam.jpg',
      ),
      FoodStoreModel(
        storeName: 'GS25',
        location: '3루 124구역',
        type: '편의점',
        storePhoto: 'assets/images/logo/gs25_logo.png',
      ),
      FoodStoreModel(
        storeName: '구루닭',
        location: '3루 116구역',
        type: '닭구이',
        storePhoto: 'assets/images/logo/gurudak.png',
      ),
      FoodStoreModel(
        storeName: '농심가락',
        location: '3루 122구역',
        type: '국수',
        storePhoto: 'assets/images/logo/nongsim2.png',
      ),
      FoodStoreModel(
        storeName: '마성떡볶이',
        location: '1층 113구역',
        type: '떡볶이',
        storePhoto: 'assets/images/logo/masung.jpg',
      ),
      FoodStoreModel(
        storeName: '브리쉘프라이',
        location: '3루 120구역',
        type: '감자튀김',
        storePhoto: 'assets/images/logo/brussels.jpg',
      ),
      FoodStoreModel(
        storeName: '요아정',
        location: '3루 118구역',
        type: '요거트 아이스크림',
        storePhoto: 'assets/images/logo/yoajung.png',
      ),
      FoodStoreModel(
        storeName: '자담치킨',
        location: '1층 114구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/jadam.jpg',
      ),
      FoodStoreModel(
        storeName: 'BBQ치킨',
        location: '2층 211구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/bbq.jpg',
      ),
      FoodStoreModel(
        storeName: 'EST1985이닝스',
        location: '2층 201구역',
        type: '펍',
        storePhoto: 'assets/images/logo/innings.png',
      ),
      FoodStoreModel(storeName: 'EXPRESS', location: '1루 2층 201구역', type: '스낵'),
      FoodStoreModel(
        storeName: '더본베이커리',
        location: '1루 2층 203구역',
        type: '크림새우, 음료',
        storePhoto: 'assets/images/logo/theborn.jpg',
      ),
      FoodStoreModel(
        storeName: '자담치킨',
        location: '1루 2층 202구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/jadam.jpg',
      ),
      FoodStoreModel(
        storeName: '고투웍',
        location: '3루 2층 더본테이스티',
        type: '중식',
        storePhoto: 'assets/images/logo/gotowok_logo.png',
      ),
      FoodStoreModel(
        storeName: '백스비어',
        location: '3루 2층 더본테이스티',
        type: '맥주',
        storePhoto: 'assets/images/logo/paikbeer_logo.png',
      ),
      FoodStoreModel(
        storeName: '빽보이피자',
        location: '3루 2층 더본테이스티',
        type: '피자',
        storePhoto: 'assets/images/logo/paikboy.jpg',
      ),
      FoodStoreModel(
        storeName: '새마을식당',
        location: '3루 2층 더본테이스티',
        type: '고기',
        storePhoto: 'assets/images/logo/saemaul.png',
      ),
      FoodStoreModel(
        storeName: '역전우동',
        location: '3루 2층 더본테이스티',
        type: '우동',
        storePhoto: 'assets/images/logo/yeokjun.png',
      ),
      FoodStoreModel(
        storeName: '연돈볼카츠',
        location: '3루 2층 더본테이스티',
        type: '카츠',
        storePhoto: 'assets/images/logo/ball.png',
      ),
      FoodStoreModel(
        storeName: '한신포차',
        location: '3루 2층 더본테이스티',
        type: '포차',
        storePhoto: 'assets/images/logo/hansin.png',
      ),
      FoodStoreModel(
        storeName: '스플래시존',
        location: '4층 스플래시존',
        type: '바,스낵',
        storePhoto: 'assets/images/logo/splash.PNG',
      ),
      FoodStoreModel(
        storeName: 'GS25',
        location: '1층 외부',
        type: '편의점',
        storePhoto: 'assets/images/logo/gs25_logo.png',
      ),
      FoodStoreModel(
        storeName: '빽다방 빵연구소',
        location: '1층 외부',
        type: '빵',
        storePhoto: 'assets/images/logo/paiksbbang.png',
      ),
    ],

    '챔피언스필드': [
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '1루 3층 104블럭',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: 'CU',
        location: '1루 3층 109블럭',
        type: '편의점',
        storePhoto: 'assets/images/logo/cu.jpg',
      ),
      FoodStoreModel(
        storeName: 'STATION',
        location: '1루 3층 106블럭',
        type: '크림새우',
        storePhoto: 'assets/images/logo/station.png',
      ),
      FoodStoreModel(
        storeName: 'XOXO핫도그',
        location: '1루 3층 108블럭',
        type: '핫도그',
        storePhoto: 'assets/images/logo/xoxo.jpg',
      ),
      FoodStoreModel(
        storeName: '마성떡볶이',
        location: '1루 3층 110블럭',
        type: '분식',
        storePhoto: 'assets/images/logo/masung.jpg',
      ),
      FoodStoreModel(
        storeName: '스트릿츄러스',
        location: '1루 3층 103블럭',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(
        storeName: '마왕족발',
        location: '1루 3층 111블럭',
        type: '족발',
        storePhoto: 'assets/images/logo/mawang.png',
      ),
      FoodStoreModel(
        storeName: '파파존스',
        location: '1루 3층 112블럭',
        type: '피자',
        storePhoto: 'assets/images/logo/papajons.png',
      ),
      FoodStoreModel(
        storeName: 'XOXO핫도그',
        location: '1루 4층',
        type: '핫도그',
        storePhoto: 'assets/images/logo/xoxo.jpg',
      ),
      FoodStoreModel(storeName: '광주원샷', location: '1루 4층', type: '치킨'),
      FoodStoreModel(
        storeName: '자문밖',
        location: '1루 4층',
        type: '삼겹정식',
        storePhoto: 'assets/images/logo/jamoon.png',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '1루 5층',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: '파파존스',
        location: '1루 5층',
        type: '피자',
        storePhoto: 'assets/images/logo/papajons.png',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '3루 3층 116블럭',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(
        storeName: '요아정',
        location: '3루 3층 123블럭',
        type: '요거트 아이스크림',
        storePhoto: 'assets/images/logo/yoajung.png',
      ),
      FoodStoreModel(
        storeName: 'CU',
        location: '3루 3층 121블럭',
        type: '편의점',
        storePhoto: 'assets/images/logo/cu.jpg',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨 PUB',
        location: '3루 3층 122블럭',
        type: '치킨 펍',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(storeName: '광주원샷', location: '3루 3층 117블럭', type: '치킨'),
      FoodStoreModel(
        storeName: '스트릿츄러스',
        location: '3루 3층 119블럭',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(
        storeName: '마성떡볶이',
        location: '3루 3층',
        type: '분식',
        storePhoto: 'assets/images/logo/masung.jpg',
      ),
      FoodStoreModel(
        storeName: '프랭크버거',
        location: '3루 3층 123블럭',
        type: '햄버거',
        storePhoto: 'assets/images/logo/frank.png',
      ),
      FoodStoreModel(storeName: '광주원샷', location: '3루 4층', type: '치킨'),
      FoodStoreModel(
        storeName: '자문밖',
        location: '3루 4층',
        type: '삼겹정식',
        storePhoto: 'assets/images/logo/jamoon.png',
      ),
      FoodStoreModel(
        storeName: '프랭크버거',
        location: '3루 4층 ',
        type: '햄버거',
        storePhoto: 'assets/images/logo/frank.png',
      ),
      FoodStoreModel(
        storeName: 'CU',
        location: '3루 5층 ',
        type: '편의점',
        storePhoto: 'assets/images/logo/cu.jpg',
      ),
      FoodStoreModel(
        storeName: '마성떡볶이',
        location: '3루 5층 ',
        type: '분식',
        storePhoto: 'assets/images/logo/masung.jpg',
      ),
      FoodStoreModel(
        storeName: 'INC COFFEE',
        location: '외부',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/ink.png',
      ),
    ],

    '라이온즈 파크': [
      FoodStoreModel(
        storeName: '맘스터치',
        location: '2층 외부',
        type: '버거,치킨',
        storePhoto: 'assets/images/logo/moms.webp',
      ),
      FoodStoreModel(storeName: '버터우드커피1', location: '2층 외부', type: '아이스크림'),
      FoodStoreModel(storeName: 'WOKSTER', location: '2층 외부', type: '아메리칸 중식'),
      FoodStoreModel(
        storeName: '브리쉘프라이',
        location: '2층 외부',
        type: '감자튀김',
        storePhoto: 'assets/images/logo/brussels.jpg',
      ),
      FoodStoreModel(storeName: '버터우드커피2', location: '2층 외야 외부', type: '아이스크림'),
      FoodStoreModel(
        storeName: '스트릿츄러스',
        location: '2층 외야 외부',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(
        storeName: '알통떡강정',
        location: '2층 외부',
        type: '닭강정',
        storePhoto: 'assets/images/logo/altong.png',
      ),
      FoodStoreModel(
        storeName: 'CU',
        location: '2층 푸드스트릿',
        type: '편의점',
        storePhoto: 'assets/images/logo/cu.jpg',
      ),
      FoodStoreModel(
        storeName: '북촌손만두',
        location: '2층 푸드스트릿',
        type: '만두',
        storePhoto: 'assets/images/logo/bookchon.png',
      ),
      FoodStoreModel(storeName: '리얼키친더홍', location: '2층 푸드스트릿', type: '분식'),
      FoodStoreModel(
        storeName: '파파존스',
        location: '2층 푸드스트릿',
        type: '피자',
        storePhoto: 'assets/images/logo/papajons.png',
      ),
      FoodStoreModel(
        storeName: '해피치즈스마일',
        location: '2층 푸드스트릿',
        type: '분식',
        storePhoto: 'assets/images/logo/happy.png',
      ),
      FoodStoreModel(storeName: '만재네', location: '외야 RF9', type: '구이'),
      FoodStoreModel(storeName: 'BLUE LION', location: '외야 RF9', type: '생맥주'),
      FoodStoreModel(
        storeName: 'MONTBLANC DE PARIS',
        location: '외야 LF9',
        type: '디저트',
        storePhoto: 'assets/images/logo/monblanc.png',
      ),
      FoodStoreModel(storeName: '테라생맥주', location: '외야 LF9', type: '생맥주'),
      FoodStoreModel(storeName: '해피크레페', location: '외야 LF5', type: '크레페'),
      FoodStoreModel(storeName: '테라생맥주', location: '외야 LF5', type: '생맥주'),
      FoodStoreModel(storeName: '땅땅치킨', location: '외야 루프탑', type: '치킨'),
      FoodStoreModel(storeName: '전설스낵', location: '1루 테이블석 2구역', type: '스낵'),
      FoodStoreModel(storeName: '5직떡볶이', location: '1루 테이블석 2구역', type: '분식'),
      FoodStoreModel(
        storeName: 'CU',
        location: '1루 원정응원석 2구역 ',
        type: '편의점',
        storePhoto: 'assets/images/logo/cu.jpg',
      ),
      FoodStoreModel(
        storeName: '노랑통닭',
        location: '1루 원정응원석 3구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/norang.png',
      ),
      FoodStoreModel(
        storeName: '북촌손만두',
        location: '3루 테이블석 2구역',
        type: '만두',
        storePhoto: 'assets/images/logo/bookchon.png',
      ),
      FoodStoreModel(
        storeName: 'Bluedog',
        location: '3루 테이블석 2구역',
        type: '핫도그',
      ),
      FoodStoreModel(storeName: '전설스낵', location: '3루 테이블석 3구역', type: '스낵'),
      FoodStoreModel(storeName: '리얼피그', location: '3루 테이블석 4구역', type: '스낵'),
      FoodStoreModel(storeName: '5직떡볶이', location: '3루 테이블석 4구역', type: '분식'),
      FoodStoreModel(
        storeName: '알통떡강정',
        location: '3루 테이블석 4구역',
        type: '닭강정',
        storePhoto: 'assets/images/logo/altong.png',
      ),
      FoodStoreModel(storeName: '버터우드커피', location: '블루존 4구역', type: '커피,음료'),
      FoodStoreModel(
        storeName: '해피치즈스마일',
        location: '블루존 5구역',
        type: '아이스크림',
        storePhoto: 'assets/images/logo/happy.png',
      ),
      FoodStoreModel(storeName: '전설꼬치', location: '블루존 6구역', type: '꼬치'),
      FoodStoreModel(storeName: '리얼누들', location: '블루존 6구역', type: '분식'),
      FoodStoreModel(
        storeName: '노랑통닭',
        location: '블루존 6구역',
        type: '치킨',
        storePhoto: 'assets/images/logo/norang.png',
      ),
      FoodStoreModel(storeName: '빙수집', location: '5층 3루 스카이 3구역', type: '빙수'),
      FoodStoreModel(
        storeName: '리얼키친비어',
        location: '5층 3루 스카이 3구역',
        type: '생맥주',
      ),
      FoodStoreModel(
        storeName: '스트릿츄러스',
        location: '5층 3루 스카이 113구역',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(
        storeName: '요아정',
        location: '5층 3루 스카이 3구역',
        type: '요거트 아이스크림',
        storePhoto: 'assets/images/logo/yoajung.png',
      ),
      FoodStoreModel(
        storeName: '호남원조식당',
        location: '5층 3루 스카이 3구역',
        type: '분식',
      ),
      FoodStoreModel(
        storeName: '스테이션',
        location: '5층 3루 스카이 21구역',
        type: '크림새우',
        storePhoto: 'assets/images/logo/station.png',
      ),
      FoodStoreModel(
        storeName: '장여사 분식',
        location: '5층 3루 스카이 21구역',
        type: '분식',
      ),
      FoodStoreModel(storeName: '파티플로어석', location: '4층 3루', type: '뷔페'),
    ],

    '창원NC파크': [
      FoodStoreModel(
        storeName: '기린이치방',
        location: '1루 1층  107블럭',
        type: '생맥주',
        storePhoto: 'assets/images/logo/kirin.png',
      ),
      FoodStoreModel(
        storeName: '디핀다트',
        location: '1루 1층 106블럭',
        type: '구슬아이스크림',
        storePhoto: 'assets/images/logo/dippin.png',
      ),
      FoodStoreModel(storeName: '리얼피그', location: '1루 1층 110블럭', type: '치킨'),
      FoodStoreModel(
        storeName: '메타킹 커피',
        location: '1루 1층 111블럭',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/metaking.jpg',
      ),
      FoodStoreModel(
        storeName: '반올림피자',
        location: '1루 1층 103블럭',
        type: '피자',
        storePhoto: 'assets/images/logo/banolim.jpg',
      ),
      FoodStoreModel(
        storeName: '싸움의고수',
        location: '1루 1층 102블럭',
        type: '보쌈',
        storePhoto: 'assets/images/logo/fight.jpeg',
      ),
      FoodStoreModel(
        storeName: '알통떡강정',
        location: '1루 1층 104블럭',
        type: '닭강정',
        storePhoto: 'assets/images/logo/altong.png',
      ),
      FoodStoreModel(storeName: '제일버거', location: '1루 1층 101블럭', type: '햄버거'),
      FoodStoreModel(
        storeName: '죠스떡볶이',
        location: '1루 1층 108블럭',
        type: '분식',
        storePhoto: 'assets/images/logo/shark.png',
      ),
      FoodStoreModel(
        storeName: '켈리 생맥주',
        location: '1루 1층 111블럭',
        type: '생맥주',
        storePhoto: 'assets/images/logo/kelly.jpeg',
      ),
      FoodStoreModel(storeName: '리얼피그', location: '3루 1층 116블럭', type: '치킨'),
      FoodStoreModel(
        storeName: '맘스터치',
        location: '3루 1층 115블럭',
        type: '햄버거',
        storePhoto: 'assets/images/logo/moms.webp',
      ),
      FoodStoreModel(
        storeName: '반올림피자',
        location: '3루 1층 119블럭',
        type: '피자',
        storePhoto: 'assets/images/logo/banolim.jpg',
      ),
      FoodStoreModel(
        storeName: '쉬림프쉐프',
        location: '3루 1층 GATE4',
        type: '크림새우',
        storePhoto: 'assets/images/logo/shirimp.png',
      ),
      FoodStoreModel(storeName: '코아양과', location: '3루 1층 116블럭', type: '밀크셰이크'),
      FoodStoreModel(
        storeName: '투다리',
        location: '3루 1층 115블럭',
        type: '꼬치',
        storePhoto: 'assets/images/logo/twodari.png',
      ),
      FoodStoreModel(
        storeName: '편밀밀',
        location: '3루 1층 GATE4',
        type: '라자냐',
        storePhoto: 'assets/images/logo/milmil.png',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '중앙 1층 114블럭',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(storeName: '공룡상회', location: '중앙 1층 113블럭', type: '편의점'),
      FoodStoreModel(storeName: '리얼피그', location: '중앙 1층 112블럭', type: '치킨'),
      FoodStoreModel(
        storeName: '스트릿츄러스',
        location: '중앙 1층 113블럭',
        type: '츄러스',
        storePhoto: 'assets/images/logo/street.jpg',
      ),
      FoodStoreModel(
        storeName: '알통떡강정',
        location: '중앙 1층 114블럭',
        type: '닭강정',
        storePhoto: 'assets/images/logo/altong.png',
      ),
      FoodStoreModel(
        storeName: 'BHC치킨',
        location: '2층 207블럭',
        type: '치킨',
        storePhoto: 'assets/images/logo/bhc.png',
      ),
      FoodStoreModel(storeName: '공룡상회', location: '2층 213블럭', type: '편의점'),
      FoodStoreModel(storeName: '생맥주', location: '2층 214블럭', type: '생맥주'),
      FoodStoreModel(
        storeName: '스타벅스',
        location: '2층 223블럭',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/starbucks.png',
      ),
      FoodStoreModel(
        storeName: '알통떡강정',
        location: '2층 209블럭',
        type: '닭강정',
        storePhoto: 'assets/images/logo/altong.png',
      ),
      FoodStoreModel(
        storeName: '죠스떡볶이',
        location: '2층 220블럭',
        type: '분식',
        storePhoto: 'assets/images/logo/shark.png',
      ),
    ],

    '사직야구장': [
      FoodStoreModel(
        storeName: '땅땅치킨',
        location: '1층 중앙광장',
        type: '치킨',
        storePhoto: 'assets/images/logo/ttangttang.png',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐',
        location: '1층 중앙광장',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(storeName: '자이언츠 카페', location: '1층 중앙광장', type: '커피,음료'),
      FoodStoreModel(storeName: '가온밀면', location: '1루 2층 124GATE', type: '밀면'),
      FoodStoreModel(storeName: '남도포차', location: '1루 2층 125GATE', type: '포차'),
      FoodStoreModel(storeName: '동래라거', location: '1루 2층 123GATE', type: '맥주'),
      FoodStoreModel(
        storeName: '땅땅치킨',
        location: '1루 2층 126GATE',
        type: '치킨',
        storePhoto: 'assets/images/logo/ttangttang.png',
      ),
      FoodStoreModel(
        storeName: '밀락당',
        location: '1루 2층 123GATE',
        type: '베이커리',
        storePhoto: 'assets/images/logo/millacdang.png',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐',
        location: '1루 2층 122GATE',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(
        storeName: '파파존스',
        location: '1루 2층 125GATE',
        type: '피자',
        storePhoto: 'assets/images/logo/papajons.png',
      ),
      FoodStoreModel(
        storeName: '반할새우',
        location: '1루 2층 124GATE',
        type: '크림새우',
      ),
      FoodStoreModel(
        storeName: '크리스피도넛',
        location: '1루 2층 125GATE',
        type: '도넛',
        storePhoto: 'assets/images/logo/krispy.jpg',
      ),
      FoodStoreModel(storeName: '남도포차', location: '3루 2층 324GATE', type: '포차'),
      FoodStoreModel(
        storeName: '다리집',
        location: '3루 2층 323GATE',
        type: '분식',
        storePhoto: 'assets/images/logo/darizip.jpeg',
      ),
      FoodStoreModel(
        storeName: '보영만두',
        location: '3루 2층 326GATE',
        type: '만두,쫄면',
        storePhoto: 'assets/images/logo/boyoung.jpeg',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐',
        location: '3루 2층 322GATE',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(storeName: '남도포차', location: '3루 2층 324GATE', type: '포차'),
      FoodStoreModel(
        storeName: '다리집',
        location: '1루 3층 131GATE',
        type: '분식',
        storePhoto: 'assets/images/logo/darizip.jpeg',
      ),
      FoodStoreModel(storeName: '동래라거', location: '1루 3층 131GATE', type: '맥주'),
      FoodStoreModel(
        storeName: '정선수제닭강정',
        location: '1루 3층 131GATE',
        type: '닭강정',
      ),
      FoodStoreModel(
        storeName: '포도&베이커스',
        location: '1루 3층 131GATE',
        type: '베이커리',
        storePhoto: 'assets/images/logo/podo.png',
      ),
      FoodStoreModel(
        storeName: '프루토프루타',
        location: '1루 3층 132GATE',
        type: '빙수',
        storePhoto: 'assets/images/logo/fruto.jpg',
      ),
      FoodStoreModel(
        storeName: '버거샵',
        location: '1루 3층 032GATE',
        type: '햄버거',
        storePhoto: 'assets/images/logo/burgershop.jpg',
      ),
      FoodStoreModel(
        storeName: '트레져스커피',
        location: '1루 3층 032GATE',
        type: '커피,음료',
        storePhoto: 'assets/images/logo/treasures.webp',
      ),
      FoodStoreModel(
        storeName: '땅땅치킨',
        location: '3루 3층 331GATE',
        type: '치킨',
        storePhoto: 'assets/images/logo/ttangttang.png',
      ),
      FoodStoreModel(
        storeName: '세븐일레븐',
        location: '3루 3층 331GATE',
        type: '편의점',
        storePhoto: 'assets/images/logo/7eleven.png',
      ),
      FoodStoreModel(
        storeName: '스테프핫도그',
        location: '3루 3층 331GATE',
        type: '핫도그',
        storePhoto: 'assets/images/logo/steff.jpg',
      ),
      FoodStoreModel(
        storeName: '심바다',
        location: '3루 3층 331GATE',
        type: '초밥',
        storePhoto: 'assets/images/logo/simbada.webp',
      ),
      FoodStoreModel(
        storeName: '보영만두',
        location: '외야 724GATE',
        type: '만두,쫄면',
        storePhoto: 'assets/images/logo/boyoung.jpeg',
      ),
      FoodStoreModel(
        storeName: '불독스테이크',
        location: '외야 723GATE',
        type: '스테이크',
        storePhoto: 'assets/images/logo/buldog.jpg',
      ),
      FoodStoreModel(
        storeName: '코카모메',
        location: '외야 924GATE',
        type: '텐동',
        storePhoto: 'assets/images/logo/coca.jpeg',
      ),
      FoodStoreModel(
        storeName: '투다리',
        location: '외야 923GATE',
        type: '스낵',
        storePhoto: 'assets/images/logo/twodari.png',
      ),
    ],
  };

  FoodStoreModel? _selectedStore;

  List<FoodStoreModel> getStore(String category) {
    return _foodStoreList[category] ?? [];
  }

  FoodStoreModel? get selectedStore => _selectedStore;

  void selectStore(FoodStoreModel food) {
    _selectedStore = food;
    notifyListeners();
  }

  void clearSelectStore() {
    _selectedStore = null;
    notifyListeners();
  }
}
