import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:lockerroom/const/color.dart';
import 'package:lockerroom/model/team_model.dart';

class TeamProvider with ChangeNotifier {
  String? _team;

  String? get team => _team;

  Future<void> loadTeam(String userId) async {
    final doc = await FirebaseFirestore.instance
        .collection('users')
        .doc(userId)
        .get();
    if (doc.exists && doc.data()?['team'] != null) {
      _team = doc['team'];
    }
    notifyListeners();
  }

  final Map<String, List<TeamModel>> _teamList = {
    'team': [
      TeamModel(
        name: 'LAD',
        symplename: 'LAD',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/lad.png',
        calenderLogo: 'assets/images/logo/lad.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: 'SD',
        symplename: 'SD',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/sd.png',
        calenderLogo: 'assets/images/logo/sd.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '대한민국',
        symplename: '대한민국',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/korea.jpg',
        calenderLogo: 'assets/images/logo/korea_calender.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '일본',
        symplename: '일본',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/japan.png',
        calenderLogo: 'assets/images/logo/japan.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '미국',
        symplename: '미국',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/usa.png',
        calenderLogo: 'assets/images/logo/usa.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '이스라엘',
        symplename: '이스라엘',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/israel.png',
        calenderLogo: 'assets/images/logo/israel.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '멕시코',
        symplename: '멕시코',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/mexico.png',
        calenderLogo: 'assets/images/logo/mexico.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '인도네시아',
        symplename: '인도네시아',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/indonesia.png',
        calenderLogo: 'assets/images/logo/indonesia.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '베네수엘라',
        symplename: '베네수엘라',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/venezuela.png',
        calenderLogo: 'assets/images/logo/venezuela.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '파키스탄',
        symplename: '파키스탄',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/pakistan.png',
        calenderLogo: 'assets/images/logo/pakistan.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '네덜란드',
        symplename: '네덜란드',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/nederland.png',
        calenderLogo: 'assets/images/logo/nederland.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '캐나다',
        symplename: '캐나다',
        stadium: '도쿄돔',
        logoPath: 'assets/images/logo/canada.png',
        calenderLogo: 'assets/images/logo/canada.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),

      TeamModel(
        name: '체코',
        symplename: '체코',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/cheko.png',
        calenderLogo: 'assets/images/logo/cheko.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '호주',
        symplename: '호주',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/aust.png',
        calenderLogo: 'assets/images/logo/aust.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '대만',
        symplename: '대만',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/tai.png',
        calenderLogo: 'assets/images/logo/tai.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '도미니카',
        symplename: '도미니카',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/dominica.png',
        calenderLogo: 'assets/images/logo/dominica.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '쿠바',
        symplename: '쿠바',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/cuba.png',
        calenderLogo: 'assets/images/logo/cuba.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '태국',
        symplename: '태국',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/thailand.png',
        calenderLogo: 'assets/images/logo/cuba.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '홍콩',
        symplename: '홍콩',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/hongkong.png',
        calenderLogo: 'assets/images/logo/hongkong.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '중국',
        symplename: '중국',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/logo/china.png',
        calenderLogo: 'assets/images/logo/china.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'KBO',
        youtubeUrl: 'https://www.youtube.com/@KBO1982/videos',
        channelId: 'UCoVz66yWHzVsXAFG8WhJK9g',
        color: korea,
      ),
      TeamModel(
        name: '두산베어스',
        symplename: '두산',
        stadium: '잠실야구장',
        logoPath: 'assets/images/korean_logo/bears.png',
        calenderLogo: 'assets/images/korean_logo/bears.png',
        symbolPath: 'assets/images/symbol/newlogo2.png',
        youtubeName: 'BEARS TV',
        youtubeUrl: 'https://www.youtube.com/@bearstv1982',
        channelId: 'UCsebzRfMhwYfjeBIxNX1brg',
        color: Doosan,
        stadium3d: 'assets/3d/jamsildoosan.png',
      ),
      TeamModel(
        name: '삼성라이온즈',
        symplename: '삼성',
        stadium: '라이온즈 파크',
        logoPath: 'assets/images/korean_logo/lions.png',
        calenderLogo: 'assets/images/korean_logo/lions.png',
        symbolPath: 'assets/images/symbol/samsung_symbol.png',
        youtubeName: 'LIONS TV',
        youtubeUrl: 'https://www.youtube.com/@lionstv1982',
        channelId: 'UCMWAku3a3h65QpLm63Jf2pw',
        color: Samsung,
      ),
      TeamModel(
        name: '롯데자이언츠',
        symplename: '롯데',
        stadium: '사직야구장',
        logoPath: 'assets/images/korean_logo/giants.png',
        calenderLogo: 'assets/images/korean_logo/giants.png',
        symbolPath: 'assets/images/symbol/lotte_symbol.png',
        youtubeName: '자이언츠 TV',
        youtubeUrl: 'https://www.youtube.com/@giantstv',
        channelId: 'UCAZQZdSY5_YrziMPqXi-Zfw',
        color: Lotte,
      ),
      TeamModel(
        name: '기아타이거즈',
        symplename: '기아',
        stadium: '챔피언스필드',
        logoPath: 'assets/images/korean_logo/tigers.png',
        calenderLogo: 'assets/images/korean_logo/tigers.png',
        symbolPath: 'assets/images/symbol/kia_symbol.png',
        youtubeName: '갸티비',
        youtubeUrl: 'https://www.youtube.com/@kiatigerstv',
        channelId: 'UCKp8knO8a6tSI1oaLjfd9XA',
        color: Kia,
      ),
      TeamModel(
        name: 'LG트윈스',
        symplename: 'LG',
        stadium: '잠실야구장',
        logoPath: 'assets/images/korean_logo/twins.png',
        calenderLogo: 'assets/images/korean_logo/twins.png',
        symbolPath: 'assets/images/symbol/lg_symbol.png',
        youtubeName: 'LGTWINSTV',
        youtubeUrl: 'https://www.youtube.com/@LGTwinsTV',
        channelId: 'UCL6QZZxb-HR4hCh_eFAnQWA',
        color: LG,
        stadium3d: 'assets/3d/jamsillg.png',
      ),
      TeamModel(
        name: 'SSG랜더스',
        symplename: 'SSG',
        stadium: '랜더스필드',
        logoPath: 'assets/images/korean_logo/landers.png',
        calenderLogo: 'assets/images/korean_logo/landers.png',
        symbolPath: 'assets/images/symbol/landers_symbol.png',
        youtubeName: '쓱튜브',
        youtubeUrl: 'https://www.youtube.com/@SSGLANDERS',
        channelId: 'UCt8iRtgjVqm5rJHNl1TUojg',
        color: Landers,
        stadium3d: 'assets/3d/landersfield.png',
      ),
      TeamModel(
        name: 'SK와이번스',
        symplename: 'SK',
        stadium: '인천SK행복드림구장',
        logoPath: 'assets/images/korean_logo/wivers.png',
        calenderLogo: 'assets/images/korean_logo/wivers.png',
        symbolPath: 'assets/images/symbol/landers_symbol.png',
        youtubeName: '쓱튜브',
        youtubeUrl: 'https://www.youtube.com/@SSGLANDERS',
        channelId: 'UCt8iRtgjVqm5rJHNl1TUojg',
        color: Landers,
        stadium3d: 'assets/3d/landersfield.png',
      ),
      TeamModel(
        name: '한화이글스',
        symplename: '한화',
        stadium: '한화생명볼파크',
        logoPath: 'assets/images/korean_logo/eagles.png',
        calenderLogo: 'assets/images/korean_logo/eagles.png',
        symbolPath: 'assets/images/symbol/hanwha_symbol.png',
        youtubeName: 'Eagles TV',
        youtubeUrl: 'https://www.youtube.com/@HanwhaEagles_official',
        channelId: 'UCdq4Ji3772xudYRUatdzRrg',
        color: Eagles,
        stadium3d: 'assets/3d/deajeon.png',
      ),
      TeamModel(
        name: '키움히어로즈',
        symplename: '키움',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/korean_logo/heroes.png',
        calenderLogo: 'assets/images/korean_logo/heroes.png',
        symbolPath: 'assets/images/symbol/kiwoom_symbol.png',
        youtubeName: '큠튜브',
        youtubeUrl: 'https://www.youtube.com/@heroesbaseballclub',
        channelId: 'UC_MA8-XEaVmvyayPzG66IKg',
        color: KIWOOM,
        stadium3d: 'assets/3d/gocheok.png',
      ),
      TeamModel(
        name: '넥센히어로즈',
        symplename: '넥센',
        stadium: '고척스카이돔',
        logoPath: 'assets/images/korean_logo/heroes.png',
        calenderLogo: 'assets/images/logo/heroes.png',
        symbolPath: 'assets/images/symbol/kiwoom_symbol.png',
        youtubeName: '큠튜브',
        youtubeUrl: 'https://www.youtube.com/@heroesbaseballclub',
        channelId: 'UC_MA8-XEaVmvyayPzG66IKg',
        color: KIWOOM,
        stadium3d: 'assets/3d/gocheok.png',
      ),

      TeamModel(
        name: 'NC다이노스',
        symplename: 'NC',
        stadium: '창원NC파크',
        logoPath: 'assets/images/korean_logo/dinos.png',
        calenderLogo: 'assets/images/korean_logo/dinos.png',
        symbolPath: 'assets/images/symbol/nc_symbol.png',
        youtubeName: '엔튜브',
        youtubeUrl: 'https://www.youtube.com/@ncdinos',
        channelId: 'UC8_FRgynMX8wlGsU6Jh3zKg',
        color: NC,
      ),

      TeamModel(
        name: 'KT위즈',
        symplename: 'KT',
        stadium: '위즈파크',
        logoPath: 'assets/images/korean_logo/wiz.png',
        calenderLogo: 'assets/images/korean_logo/wiz.png',
        symbolPath: 'assets/images/symbol/kt_symbol.png',
        youtubeName: 'kt wiz - 위즈TV',
        youtubeUrl: 'https://www.youtube.com/@ktwiztv',
        channelId: 'UCvScyjGkBUx2CJDMNAi9Twg',
        color: KT,
      ),
    ],
  };

  TeamModel? _selectedTeam;

  List<TeamModel> getTeam(String category) {
    return _teamList[category] ?? [];
  }

  TeamModel? get selectedTeam => _selectedTeam;

  void selectTeam(TeamModel team) {
    _selectedTeam = team;
    notifyListeners();
  }

  // 팀 이름으로 TeamModel 찾기
  TeamModel? findTeamByName(String name) {
    final teams = _teamList['team'] ?? [];
    try {
      return teams.firstWhere((t) => t.symplename == name);
    } catch (_) {
      return null;
    }
  }

  Future<void> setTeam(String team) async {
    _team = team;
    notifyListeners();
  }
}
